// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: services/users.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"` // e.g. for filtering or autocomplete
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_services_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_services_users_proto_rawDescGZIP(), []int{0}
}

func (x *ListUsersRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ListUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserInfo            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_services_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_services_users_proto_rawDescGZIP(), []int{1}
}

func (x *ListUsersResponse) GetUsers() []*UserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_services_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_services_users_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_services_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_services_users_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_services_users_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_users_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_services_users_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteUserResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetUserCasbinContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserCasbinContextRequest) Reset() {
	*x = GetUserCasbinContextRequest{}
	mi := &file_services_users_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserCasbinContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCasbinContextRequest) ProtoMessage() {}

func (x *GetUserCasbinContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_users_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCasbinContextRequest.ProtoReflect.Descriptor instead.
func (*GetUserCasbinContextRequest) Descriptor() ([]byte, []int) {
	return file_services_users_proto_rawDescGZIP(), []int{5}
}

type GetUserPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPermissionRequest) Reset() {
	*x = GetUserPermissionRequest{}
	mi := &file_services_users_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPermissionRequest) ProtoMessage() {}

func (x *GetUserPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_users_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPermissionRequest.ProtoReflect.Descriptor instead.
func (*GetUserPermissionRequest) Descriptor() ([]byte, []int) {
	return file_services_users_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserPermissionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SetUserPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Permissions   []string               `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserPermissionRequest) Reset() {
	*x = SetUserPermissionRequest{}
	mi := &file_services_users_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserPermissionRequest) ProtoMessage() {}

func (x *SetUserPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_users_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserPermissionRequest.ProtoReflect.Descriptor instead.
func (*SetUserPermissionRequest) Descriptor() ([]byte, []int) {
	return file_services_users_proto_rawDescGZIP(), []int{7}
}

func (x *SetUserPermissionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetUserPermissionRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type SetUserPermissionsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Permissions   []*FeaturePermissionEntry `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserPermissionsResponse) Reset() {
	*x = SetUserPermissionsResponse{}
	mi := &file_services_users_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserPermissionsResponse) ProtoMessage() {}

func (x *SetUserPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_users_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserPermissionsResponse.ProtoReflect.Descriptor instead.
func (*SetUserPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_services_users_proto_rawDescGZIP(), []int{8}
}

func (x *SetUserPermissionsResponse) GetPermissions() []*FeaturePermissionEntry {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// Response with the casbin context
type GetUserPermissionsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Permissions   []*FeaturePermissionEntry `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPermissionsResponse) Reset() {
	*x = GetUserPermissionsResponse{}
	mi := &file_services_users_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPermissionsResponse) ProtoMessage() {}

func (x *GetUserPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_users_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPermissionsResponse.ProtoReflect.Descriptor instead.
func (*GetUserPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_services_users_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserPermissionsResponse) GetPermissions() []*FeaturePermissionEntry {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type FeaturePermissionEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values        []string               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeaturePermissionEntry) Reset() {
	*x = FeaturePermissionEntry{}
	mi := &file_services_users_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeaturePermissionEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeaturePermissionEntry) ProtoMessage() {}

func (x *FeaturePermissionEntry) ProtoReflect() protoreflect.Message {
	mi := &file_services_users_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeaturePermissionEntry.ProtoReflect.Descriptor instead.
func (*FeaturePermissionEntry) Descriptor() ([]byte, []int) {
	return file_services_users_proto_rawDescGZIP(), []int{10}
}

func (x *FeaturePermissionEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *FeaturePermissionEntry) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_services_users_proto protoreflect.FileDescriptor

const file_services_users_proto_rawDesc = "" +
	"\n" +
	"\x14services/users.proto\x12\x02pb\x1a\x0fdtos/user.proto\x1a\x13services/auth.proto\x1a\x1cgoogle/api/annotations.proto\x1a google/protobuf/descriptor.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"Y\n" +
	"\x10ListUsersRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"7\n" +
	"\x11ListUsersResponse\x12\"\n" +
	"\x05users\x18\x01 \x03(\v2\f.pb.UserInfoR\x05users\"$\n" +
	"\x0eGetUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"'\n" +
	"\x11DeleteUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"$\n" +
	"\x12DeleteUserResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x1d\n" +
	"\x1bGetUserCasbinContextRequest\".\n" +
	"\x18GetUserPermissionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"P\n" +
	"\x18SetUserPermissionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vpermissions\x18\x02 \x03(\tR\vpermissions\"Z\n" +
	"\x1aSetUserPermissionsResponse\x12<\n" +
	"\vpermissions\x18\x01 \x03(\v2\x1a.pb.FeaturePermissionEntryR\vpermissions\"Z\n" +
	"\x1aGetUserPermissionsResponse\x12<\n" +
	"\vpermissions\x18\x01 \x03(\v2\x1a.pb.FeaturePermissionEntryR\vpermissions\"B\n" +
	"\x16FeaturePermissionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values2\x9a\b\n" +
	"\vUserService\x12p\n" +
	"\tListUsers\x12\x14.pb.ListUsersRequest\x1a\x15.pb.ListUsersResponse\"6\x92A\x0eb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x8a\x92\xf4\x01\v\n" +
	"\tuser:list\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/users\x12e\n" +
	"\n" +
	"CreateUser\x12\f.pb.UserInfo\x1a\f.pb.UserInfo\";\x92A\x0eb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x8a\x92\xf4\x01\r\n" +
	"\vuser:create\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/users\x12l\n" +
	"\n" +
	"UpdateUser\x12\f.pb.UserInfo\x1a\f.pb.UserInfo\"B\x92A\x0eb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x8a\x92\xf4\x01\r\n" +
	"\vuser:update\x82\xd3\xe4\x93\x02\x19:\x01*\x1a\x14/api/v1/users/{name}\x12j\n" +
	"\aGetUser\x12\x12.pb.GetUserRequest\x1a\f.pb.UserInfo\"=\x92A\x0eb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x8a\x92\xf4\x01\v\n" +
	"\tuser:read\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/users/{name}\x12~\n" +
	"\n" +
	"DeleteUser\x12\x15.pb.DeleteUserRequest\x1a\x16.pb.DeleteUserResponse\"A\x92A\x0eb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x8a\x92\xf4\x01\x0f\n" +
	"\vuser:delete\x10\x01\x82\xd3\xe4\x93\x02\x16*\x14/api/v1/users/{name}\x12\x89\x01\n" +
	"\x12GetSelfPermissions\x12\x1f.pb.GetUserCasbinContextRequest\x1a\x1e.pb.GetUserPermissionsResponse\"2\x92A\x0eb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/users/permissions\x12\x9f\x01\n" +
	"\x12GetUserPermissions\x12\x1c.pb.GetUserPermissionRequest\x1a\x1e.pb.GetUserPermissionsResponse\"K\x92A\x0eb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x8a\x92\xf4\x01\r\n" +
	"\tuser:read\x10\x01\x82\xd3\xe4\x93\x02\"\x12 /api/v1/users/{name}/permissions\x12\xa9\x01\n" +
	"\x12SetUserPermissions\x12\x1c.pb.SetUserPermissionRequest\x1a\x1e.pb.SetUserPermissionsResponse\"U\x92A\x0eb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x8a\x92\xf4\x01\x14\n" +
	"\x10user:permissions\x10\x01\x82\xd3\xe4\x93\x02%:\x01*\" /api/v1/users/{name}/permissionsB\x83\x01\x92AiZY\n" +
	"W\n" +
	"\x06bearer\x12M\b\x02\x128Authentication token, prefixed by Bearer: Bearer <token>\x1a\rAuthorization \x02b\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00Z\x15internal/managment/pbb\x06proto3"

var (
	file_services_users_proto_rawDescOnce sync.Once
	file_services_users_proto_rawDescData []byte
)

func file_services_users_proto_rawDescGZIP() []byte {
	file_services_users_proto_rawDescOnce.Do(func() {
		file_services_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_users_proto_rawDesc), len(file_services_users_proto_rawDesc)))
	})
	return file_services_users_proto_rawDescData
}

var file_services_users_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_services_users_proto_goTypes = []any{
	(*ListUsersRequest)(nil),            // 0: pb.ListUsersRequest
	(*ListUsersResponse)(nil),           // 1: pb.ListUsersResponse
	(*GetUserRequest)(nil),              // 2: pb.GetUserRequest
	(*DeleteUserRequest)(nil),           // 3: pb.DeleteUserRequest
	(*DeleteUserResponse)(nil),          // 4: pb.DeleteUserResponse
	(*GetUserCasbinContextRequest)(nil), // 5: pb.GetUserCasbinContextRequest
	(*GetUserPermissionRequest)(nil),    // 6: pb.GetUserPermissionRequest
	(*SetUserPermissionRequest)(nil),    // 7: pb.SetUserPermissionRequest
	(*SetUserPermissionsResponse)(nil),  // 8: pb.SetUserPermissionsResponse
	(*GetUserPermissionsResponse)(nil),  // 9: pb.GetUserPermissionsResponse
	(*FeaturePermissionEntry)(nil),      // 10: pb.FeaturePermissionEntry
	(*UserInfo)(nil),                    // 11: pb.UserInfo
}
var file_services_users_proto_depIdxs = []int32{
	11, // 0: pb.ListUsersResponse.users:type_name -> pb.UserInfo
	10, // 1: pb.SetUserPermissionsResponse.permissions:type_name -> pb.FeaturePermissionEntry
	10, // 2: pb.GetUserPermissionsResponse.permissions:type_name -> pb.FeaturePermissionEntry
	0,  // 3: pb.UserService.ListUsers:input_type -> pb.ListUsersRequest
	11, // 4: pb.UserService.CreateUser:input_type -> pb.UserInfo
	11, // 5: pb.UserService.UpdateUser:input_type -> pb.UserInfo
	2,  // 6: pb.UserService.GetUser:input_type -> pb.GetUserRequest
	3,  // 7: pb.UserService.DeleteUser:input_type -> pb.DeleteUserRequest
	5,  // 8: pb.UserService.GetSelfPermissions:input_type -> pb.GetUserCasbinContextRequest
	6,  // 9: pb.UserService.GetUserPermissions:input_type -> pb.GetUserPermissionRequest
	7,  // 10: pb.UserService.SetUserPermissions:input_type -> pb.SetUserPermissionRequest
	1,  // 11: pb.UserService.ListUsers:output_type -> pb.ListUsersResponse
	11, // 12: pb.UserService.CreateUser:output_type -> pb.UserInfo
	11, // 13: pb.UserService.UpdateUser:output_type -> pb.UserInfo
	11, // 14: pb.UserService.GetUser:output_type -> pb.UserInfo
	4,  // 15: pb.UserService.DeleteUser:output_type -> pb.DeleteUserResponse
	9,  // 16: pb.UserService.GetSelfPermissions:output_type -> pb.GetUserPermissionsResponse
	9,  // 17: pb.UserService.GetUserPermissions:output_type -> pb.GetUserPermissionsResponse
	8,  // 18: pb.UserService.SetUserPermissions:output_type -> pb.SetUserPermissionsResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_services_users_proto_init() }
func file_services_users_proto_init() {
	if File_services_users_proto != nil {
		return
	}
	file_dtos_user_proto_init()
	file_services_auth_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_users_proto_rawDesc), len(file_services_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_users_proto_goTypes,
		DependencyIndexes: file_services_users_proto_depIdxs,
		MessageInfos:      file_services_users_proto_msgTypes,
	}.Build()
	File_services_users_proto = out.File
	file_services_users_proto_goTypes = nil
	file_services_users_proto_depIdxs = nil
}
