// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: dtos/user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sub           string                 `protobuf:"bytes,1,opt,name=sub,proto3" json:"sub,omitempty"`                                    // Subject - unique user ID
	Iss           string                 `protobuf:"bytes,2,opt,name=iss,proto3" json:"iss,omitempty"`                                    // Issuer
	Aud           string                 `protobuf:"bytes,3,opt,name=aud,proto3" json:"aud,omitempty"`                                    // Audience
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`                                  // Preferred username
	DisplayName   string                 `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"` // Full name
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Avatar        string                 `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"` // Profile picture URL
	Address       []string               `protobuf:"bytes,8,rep,name=address,proto3" json:"address,omitempty"`
	Phone         string                 `protobuf:"bytes,9,opt,name=phone,proto3" json:"phone,omitempty"`
	Groups        []string               `protobuf:"bytes,10,rep,name=groups,proto3" json:"groups,omitempty"`
	Owner         string                 `protobuf:"bytes,11,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_dtos_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dtos_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_dtos_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetSub() string {
	if x != nil {
		return x.Sub
	}
	return ""
}

func (x *UserInfo) GetIss() string {
	if x != nil {
		return x.Iss
	}
	return ""
}

func (x *UserInfo) GetAud() string {
	if x != nil {
		return x.Aud
	}
	return ""
}

func (x *UserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfo) GetAddress() []string {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *UserInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserInfo) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *UserInfo) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

var File_dtos_user_proto protoreflect.FileDescriptor

const file_dtos_user_proto_rawDesc = "" +
	"\n" +
	"\x0fdtos/user.proto\x12\x02pb\"\x83\x02\n" +
	"\bUserInfo\x12\x10\n" +
	"\x03sub\x18\x01 \x01(\tR\x03sub\x12\x10\n" +
	"\x03iss\x18\x02 \x01(\tR\x03iss\x12\x10\n" +
	"\x03aud\x18\x03 \x01(\tR\x03aud\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x05 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x16\n" +
	"\x06avatar\x18\a \x01(\tR\x06avatar\x12\x18\n" +
	"\aaddress\x18\b \x03(\tR\aaddress\x12\x14\n" +
	"\x05phone\x18\t \x01(\tR\x05phone\x12\x16\n" +
	"\x06groups\x18\n" +
	" \x03(\tR\x06groups\x12\x14\n" +
	"\x05owner\x18\v \x01(\tR\x05ownerB\x17Z\x15internal/managment/pbb\x06proto3"

var (
	file_dtos_user_proto_rawDescOnce sync.Once
	file_dtos_user_proto_rawDescData []byte
)

func file_dtos_user_proto_rawDescGZIP() []byte {
	file_dtos_user_proto_rawDescOnce.Do(func() {
		file_dtos_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dtos_user_proto_rawDesc), len(file_dtos_user_proto_rawDesc)))
	})
	return file_dtos_user_proto_rawDescData
}

var file_dtos_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dtos_user_proto_goTypes = []any{
	(*UserInfo)(nil), // 0: pb.UserInfo
}
var file_dtos_user_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dtos_user_proto_init() }
func file_dtos_user_proto_init() {
	if File_dtos_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dtos_user_proto_rawDesc), len(file_dtos_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dtos_user_proto_goTypes,
		DependencyIndexes: file_dtos_user_proto_depIdxs,
		MessageInfos:      file_dtos_user_proto_msgTypes,
	}.Build()
	File_dtos_user_proto = out.File
	file_dtos_user_proto_goTypes = nil
	file_dtos_user_proto_depIdxs = nil
}
