// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: services/history_day_traffic_data_detection_section.service.proto

/*
Package pb is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package pb

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

var (
	filter_HistoryDayTrafficDataByDetectionSectionService_ListHistoryDayTrafficDataByDetectionSection_0 = &utilities.DoubleArray{Encoding: map[string]int{}, Base: []int(nil), Check: []int(nil)}
)

func request_HistoryDayTrafficDataByDetectionSectionService_ListHistoryDayTrafficDataByDetectionSection_0(ctx context.Context, marshaler runtime.Marshaler, client HistoryDayTrafficDataByDetectionSectionServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq ListTrafficDataByDetectionSectionRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_HistoryDayTrafficDataByDetectionSectionService_ListHistoryDayTrafficDataByDetectionSection_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.ListHistoryDayTrafficDataByDetectionSection(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_HistoryDayTrafficDataByDetectionSectionService_ListHistoryDayTrafficDataByDetectionSection_0(ctx context.Context, marshaler runtime.Marshaler, server HistoryDayTrafficDataByDetectionSectionServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq ListTrafficDataByDetectionSectionRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_HistoryDayTrafficDataByDetectionSectionService_ListHistoryDayTrafficDataByDetectionSection_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.ListHistoryDayTrafficDataByDetectionSection(ctx, &protoReq)
	return msg, metadata, err

}

var (
	filter_HistoryDayTrafficDataByDetectionSectionService_GetHistoryDayTrafficDataByDetectionSection_0 = &utilities.DoubleArray{Encoding: map[string]int{}, Base: []int(nil), Check: []int(nil)}
)

func request_HistoryDayTrafficDataByDetectionSectionService_GetHistoryDayTrafficDataByDetectionSection_0(ctx context.Context, marshaler runtime.Marshaler, client HistoryDayTrafficDataByDetectionSectionServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GetTrafficDataByDetectionSectionRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_HistoryDayTrafficDataByDetectionSectionService_GetHistoryDayTrafficDataByDetectionSection_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.GetHistoryDayTrafficDataByDetectionSection(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_HistoryDayTrafficDataByDetectionSectionService_GetHistoryDayTrafficDataByDetectionSection_0(ctx context.Context, marshaler runtime.Marshaler, server HistoryDayTrafficDataByDetectionSectionServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GetTrafficDataByDetectionSectionRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_HistoryDayTrafficDataByDetectionSectionService_GetHistoryDayTrafficDataByDetectionSection_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.GetHistoryDayTrafficDataByDetectionSection(ctx, &protoReq)
	return msg, metadata, err

}

func request_HistoryDayTrafficDataByDetectionSectionService_CreateHistoryDayTrafficDataByDetectionSection_0(ctx context.Context, marshaler runtime.Marshaler, client HistoryDayTrafficDataByDetectionSectionServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq CreateHistoryDayTrafficDataByDetectionSectionRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.CreateHistoryDayTrafficDataByDetectionSection(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_HistoryDayTrafficDataByDetectionSectionService_CreateHistoryDayTrafficDataByDetectionSection_0(ctx context.Context, marshaler runtime.Marshaler, server HistoryDayTrafficDataByDetectionSectionServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq CreateHistoryDayTrafficDataByDetectionSectionRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.CreateHistoryDayTrafficDataByDetectionSection(ctx, &protoReq)
	return msg, metadata, err

}

func request_HistoryDayTrafficDataByDetectionSectionService_UpdateHistoryDayTrafficDataByDetectionSection_0(ctx context.Context, marshaler runtime.Marshaler, client HistoryDayTrafficDataByDetectionSectionServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq UpdateHistoryDayTrafficDataByDetectionSectionRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.UpdateHistoryDayTrafficDataByDetectionSection(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_HistoryDayTrafficDataByDetectionSectionService_UpdateHistoryDayTrafficDataByDetectionSection_0(ctx context.Context, marshaler runtime.Marshaler, server HistoryDayTrafficDataByDetectionSectionServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq UpdateHistoryDayTrafficDataByDetectionSectionRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.UpdateHistoryDayTrafficDataByDetectionSection(ctx, &protoReq)
	return msg, metadata, err

}

var (
	filter_HistoryDayTrafficDataByDetectionSectionService_DeleteHistoryDayTrafficDataByDetectionSection_0 = &utilities.DoubleArray{Encoding: map[string]int{}, Base: []int(nil), Check: []int(nil)}
)

func request_HistoryDayTrafficDataByDetectionSectionService_DeleteHistoryDayTrafficDataByDetectionSection_0(ctx context.Context, marshaler runtime.Marshaler, client HistoryDayTrafficDataByDetectionSectionServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq DeleteTrafficDataByDetectionSectionRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_HistoryDayTrafficDataByDetectionSectionService_DeleteHistoryDayTrafficDataByDetectionSection_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.DeleteHistoryDayTrafficDataByDetectionSection(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_HistoryDayTrafficDataByDetectionSectionService_DeleteHistoryDayTrafficDataByDetectionSection_0(ctx context.Context, marshaler runtime.Marshaler, server HistoryDayTrafficDataByDetectionSectionServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq DeleteTrafficDataByDetectionSectionRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_HistoryDayTrafficDataByDetectionSectionService_DeleteHistoryDayTrafficDataByDetectionSection_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.DeleteHistoryDayTrafficDataByDetectionSection(ctx, &protoReq)
	return msg, metadata, err

}

func request_HistoryDayTrafficDataByDetectionSectionService_BulkCreateHistoryDayTrafficDataByDetectionSection_0(ctx context.Context, marshaler runtime.Marshaler, client HistoryDayTrafficDataByDetectionSectionServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq BulkCreateTrafficDataByDetectionSectionRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.BulkCreateHistoryDayTrafficDataByDetectionSection(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_HistoryDayTrafficDataByDetectionSectionService_BulkCreateHistoryDayTrafficDataByDetectionSection_0(ctx context.Context, marshaler runtime.Marshaler, server HistoryDayTrafficDataByDetectionSectionServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq BulkCreateTrafficDataByDetectionSectionRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.BulkCreateHistoryDayTrafficDataByDetectionSection(ctx, &protoReq)
	return msg, metadata, err

}

var (
	filter_HistoryDayTrafficDataByDetectionSectionService_GetHistoryDayTrafficDataByDetectionSectionStatistics_0 = &utilities.DoubleArray{Encoding: map[string]int{}, Base: []int(nil), Check: []int(nil)}
)

func request_HistoryDayTrafficDataByDetectionSectionService_GetHistoryDayTrafficDataByDetectionSectionStatistics_0(ctx context.Context, marshaler runtime.Marshaler, client HistoryDayTrafficDataByDetectionSectionServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GetTrafficDataByDetectionSectionStatisticsRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_HistoryDayTrafficDataByDetectionSectionService_GetHistoryDayTrafficDataByDetectionSectionStatistics_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.GetHistoryDayTrafficDataByDetectionSectionStatistics(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_HistoryDayTrafficDataByDetectionSectionService_GetHistoryDayTrafficDataByDetectionSectionStatistics_0(ctx context.Context, marshaler runtime.Marshaler, server HistoryDayTrafficDataByDetectionSectionServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GetTrafficDataByDetectionSectionStatisticsRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_HistoryDayTrafficDataByDetectionSectionService_GetHistoryDayTrafficDataByDetectionSectionStatistics_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.GetHistoryDayTrafficDataByDetectionSectionStatistics(ctx, &protoReq)
	return msg, metadata, err

}

var (
	filter_HistoryDayTrafficDataByDetectionSectionService_ListHistoryDayTrafficDataByDetectionSectionDaily_0 = &utilities.DoubleArray{Encoding: map[string]int{}, Base: []int(nil), Check: []int(nil)}
)

func request_HistoryDayTrafficDataByDetectionSectionService_ListHistoryDayTrafficDataByDetectionSectionDaily_0(ctx context.Context, marshaler runtime.Marshaler, client HistoryDayTrafficDataByDetectionSectionServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq ListTrafficDataByDetectionSectionDailyRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_HistoryDayTrafficDataByDetectionSectionService_ListHistoryDayTrafficDataByDetectionSectionDaily_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.ListHistoryDayTrafficDataByDetectionSectionDaily(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_HistoryDayTrafficDataByDetectionSectionService_ListHistoryDayTrafficDataByDetectionSectionDaily_0(ctx context.Context, marshaler runtime.Marshaler, server HistoryDayTrafficDataByDetectionSectionServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq ListTrafficDataByDetectionSectionDailyRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_HistoryDayTrafficDataByDetectionSectionService_ListHistoryDayTrafficDataByDetectionSectionDaily_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.ListHistoryDayTrafficDataByDetectionSectionDaily(ctx, &protoReq)
	return msg, metadata, err

}

var (
	filter_HistoryDayTrafficDataByDetectionSectionService_DownloadHistoryDayTrafficDataByDetectionSection_0 = &utilities.DoubleArray{Encoding: map[string]int{}, Base: []int(nil), Check: []int(nil)}
)

func request_HistoryDayTrafficDataByDetectionSectionService_DownloadHistoryDayTrafficDataByDetectionSection_0(ctx context.Context, marshaler runtime.Marshaler, client HistoryDayTrafficDataByDetectionSectionServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq DownloadTrafficDataByDetectionSectionRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_HistoryDayTrafficDataByDetectionSectionService_DownloadHistoryDayTrafficDataByDetectionSection_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.DownloadHistoryDayTrafficDataByDetectionSection(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_HistoryDayTrafficDataByDetectionSectionService_DownloadHistoryDayTrafficDataByDetectionSection_0(ctx context.Context, marshaler runtime.Marshaler, server HistoryDayTrafficDataByDetectionSectionServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq DownloadTrafficDataByDetectionSectionRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_HistoryDayTrafficDataByDetectionSectionService_DownloadHistoryDayTrafficDataByDetectionSection_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.DownloadHistoryDayTrafficDataByDetectionSection(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterHistoryDayTrafficDataByDetectionSectionServiceHandlerServer registers the http handlers for service HistoryDayTrafficDataByDetectionSectionService to "mux".
// UnaryRPC     :call HistoryDayTrafficDataByDetectionSectionServiceServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterHistoryDayTrafficDataByDetectionSectionServiceHandlerFromEndpoint instead.
func RegisterHistoryDayTrafficDataByDetectionSectionServiceHandlerServer(ctx context.Context, mux *runtime.ServeMux, server HistoryDayTrafficDataByDetectionSectionServiceServer) error {

	mux.Handle("GET", pattern_HistoryDayTrafficDataByDetectionSectionService_ListHistoryDayTrafficDataByDetectionSection_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/pb.HistoryDayTrafficDataByDetectionSectionService/ListHistoryDayTrafficDataByDetectionSection", runtime.WithHTTPPathPattern("/api/v1/traffic/history_day/detection_section/list"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_HistoryDayTrafficDataByDetectionSectionService_ListHistoryDayTrafficDataByDetectionSection_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryDayTrafficDataByDetectionSectionService_ListHistoryDayTrafficDataByDetectionSection_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_HistoryDayTrafficDataByDetectionSectionService_GetHistoryDayTrafficDataByDetectionSection_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/pb.HistoryDayTrafficDataByDetectionSectionService/GetHistoryDayTrafficDataByDetectionSection", runtime.WithHTTPPathPattern("/api/v1/traffic/history_day/detection_section/single"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_HistoryDayTrafficDataByDetectionSectionService_GetHistoryDayTrafficDataByDetectionSection_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryDayTrafficDataByDetectionSectionService_GetHistoryDayTrafficDataByDetectionSection_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_HistoryDayTrafficDataByDetectionSectionService_CreateHistoryDayTrafficDataByDetectionSection_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/pb.HistoryDayTrafficDataByDetectionSectionService/CreateHistoryDayTrafficDataByDetectionSection", runtime.WithHTTPPathPattern("/api/v1/traffic/history_day/detection_section"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_HistoryDayTrafficDataByDetectionSectionService_CreateHistoryDayTrafficDataByDetectionSection_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryDayTrafficDataByDetectionSectionService_CreateHistoryDayTrafficDataByDetectionSection_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("PATCH", pattern_HistoryDayTrafficDataByDetectionSectionService_UpdateHistoryDayTrafficDataByDetectionSection_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/pb.HistoryDayTrafficDataByDetectionSectionService/UpdateHistoryDayTrafficDataByDetectionSection", runtime.WithHTTPPathPattern("/api/v1/traffic/history_day/detection_section"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_HistoryDayTrafficDataByDetectionSectionService_UpdateHistoryDayTrafficDataByDetectionSection_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryDayTrafficDataByDetectionSectionService_UpdateHistoryDayTrafficDataByDetectionSection_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("DELETE", pattern_HistoryDayTrafficDataByDetectionSectionService_DeleteHistoryDayTrafficDataByDetectionSection_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/pb.HistoryDayTrafficDataByDetectionSectionService/DeleteHistoryDayTrafficDataByDetectionSection", runtime.WithHTTPPathPattern("/api/v1/traffic/history_day/detection_section"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_HistoryDayTrafficDataByDetectionSectionService_DeleteHistoryDayTrafficDataByDetectionSection_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryDayTrafficDataByDetectionSectionService_DeleteHistoryDayTrafficDataByDetectionSection_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_HistoryDayTrafficDataByDetectionSectionService_BulkCreateHistoryDayTrafficDataByDetectionSection_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/pb.HistoryDayTrafficDataByDetectionSectionService/BulkCreateHistoryDayTrafficDataByDetectionSection", runtime.WithHTTPPathPattern("/api/v1/traffic/history_day/detection_section/bulk"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_HistoryDayTrafficDataByDetectionSectionService_BulkCreateHistoryDayTrafficDataByDetectionSection_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryDayTrafficDataByDetectionSectionService_BulkCreateHistoryDayTrafficDataByDetectionSection_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_HistoryDayTrafficDataByDetectionSectionService_GetHistoryDayTrafficDataByDetectionSectionStatistics_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/pb.HistoryDayTrafficDataByDetectionSectionService/GetHistoryDayTrafficDataByDetectionSectionStatistics", runtime.WithHTTPPathPattern("/api/v1/traffic/history_day/detection_section/statistics"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_HistoryDayTrafficDataByDetectionSectionService_GetHistoryDayTrafficDataByDetectionSectionStatistics_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryDayTrafficDataByDetectionSectionService_GetHistoryDayTrafficDataByDetectionSectionStatistics_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_HistoryDayTrafficDataByDetectionSectionService_ListHistoryDayTrafficDataByDetectionSectionDaily_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/pb.HistoryDayTrafficDataByDetectionSectionService/ListHistoryDayTrafficDataByDetectionSectionDaily", runtime.WithHTTPPathPattern("/api/v1/traffic/history_day/detection_section/daily"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_HistoryDayTrafficDataByDetectionSectionService_ListHistoryDayTrafficDataByDetectionSectionDaily_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryDayTrafficDataByDetectionSectionService_ListHistoryDayTrafficDataByDetectionSectionDaily_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_HistoryDayTrafficDataByDetectionSectionService_DownloadHistoryDayTrafficDataByDetectionSection_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/pb.HistoryDayTrafficDataByDetectionSectionService/DownloadHistoryDayTrafficDataByDetectionSection", runtime.WithHTTPPathPattern("/api/v1/traffic/history_day/detection_section/download"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_HistoryDayTrafficDataByDetectionSectionService_DownloadHistoryDayTrafficDataByDetectionSection_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryDayTrafficDataByDetectionSectionService_DownloadHistoryDayTrafficDataByDetectionSection_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterHistoryDayTrafficDataByDetectionSectionServiceHandlerFromEndpoint is same as RegisterHistoryDayTrafficDataByDetectionSectionServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterHistoryDayTrafficDataByDetectionSectionServiceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.DialContext(ctx, endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterHistoryDayTrafficDataByDetectionSectionServiceHandler(ctx, mux, conn)
}

// RegisterHistoryDayTrafficDataByDetectionSectionServiceHandler registers the http handlers for service HistoryDayTrafficDataByDetectionSectionService to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterHistoryDayTrafficDataByDetectionSectionServiceHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterHistoryDayTrafficDataByDetectionSectionServiceHandlerClient(ctx, mux, NewHistoryDayTrafficDataByDetectionSectionServiceClient(conn))
}

// RegisterHistoryDayTrafficDataByDetectionSectionServiceHandlerClient registers the http handlers for service HistoryDayTrafficDataByDetectionSectionService
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "HistoryDayTrafficDataByDetectionSectionServiceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "HistoryDayTrafficDataByDetectionSectionServiceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "HistoryDayTrafficDataByDetectionSectionServiceClient" to call the correct interceptors.
func RegisterHistoryDayTrafficDataByDetectionSectionServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client HistoryDayTrafficDataByDetectionSectionServiceClient) error {

	mux.Handle("GET", pattern_HistoryDayTrafficDataByDetectionSectionService_ListHistoryDayTrafficDataByDetectionSection_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/pb.HistoryDayTrafficDataByDetectionSectionService/ListHistoryDayTrafficDataByDetectionSection", runtime.WithHTTPPathPattern("/api/v1/traffic/history_day/detection_section/list"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_HistoryDayTrafficDataByDetectionSectionService_ListHistoryDayTrafficDataByDetectionSection_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryDayTrafficDataByDetectionSectionService_ListHistoryDayTrafficDataByDetectionSection_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_HistoryDayTrafficDataByDetectionSectionService_GetHistoryDayTrafficDataByDetectionSection_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/pb.HistoryDayTrafficDataByDetectionSectionService/GetHistoryDayTrafficDataByDetectionSection", runtime.WithHTTPPathPattern("/api/v1/traffic/history_day/detection_section/single"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_HistoryDayTrafficDataByDetectionSectionService_GetHistoryDayTrafficDataByDetectionSection_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryDayTrafficDataByDetectionSectionService_GetHistoryDayTrafficDataByDetectionSection_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_HistoryDayTrafficDataByDetectionSectionService_CreateHistoryDayTrafficDataByDetectionSection_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/pb.HistoryDayTrafficDataByDetectionSectionService/CreateHistoryDayTrafficDataByDetectionSection", runtime.WithHTTPPathPattern("/api/v1/traffic/history_day/detection_section"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_HistoryDayTrafficDataByDetectionSectionService_CreateHistoryDayTrafficDataByDetectionSection_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryDayTrafficDataByDetectionSectionService_CreateHistoryDayTrafficDataByDetectionSection_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("PATCH", pattern_HistoryDayTrafficDataByDetectionSectionService_UpdateHistoryDayTrafficDataByDetectionSection_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/pb.HistoryDayTrafficDataByDetectionSectionService/UpdateHistoryDayTrafficDataByDetectionSection", runtime.WithHTTPPathPattern("/api/v1/traffic/history_day/detection_section"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_HistoryDayTrafficDataByDetectionSectionService_UpdateHistoryDayTrafficDataByDetectionSection_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryDayTrafficDataByDetectionSectionService_UpdateHistoryDayTrafficDataByDetectionSection_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("DELETE", pattern_HistoryDayTrafficDataByDetectionSectionService_DeleteHistoryDayTrafficDataByDetectionSection_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/pb.HistoryDayTrafficDataByDetectionSectionService/DeleteHistoryDayTrafficDataByDetectionSection", runtime.WithHTTPPathPattern("/api/v1/traffic/history_day/detection_section"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_HistoryDayTrafficDataByDetectionSectionService_DeleteHistoryDayTrafficDataByDetectionSection_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryDayTrafficDataByDetectionSectionService_DeleteHistoryDayTrafficDataByDetectionSection_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_HistoryDayTrafficDataByDetectionSectionService_BulkCreateHistoryDayTrafficDataByDetectionSection_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/pb.HistoryDayTrafficDataByDetectionSectionService/BulkCreateHistoryDayTrafficDataByDetectionSection", runtime.WithHTTPPathPattern("/api/v1/traffic/history_day/detection_section/bulk"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_HistoryDayTrafficDataByDetectionSectionService_BulkCreateHistoryDayTrafficDataByDetectionSection_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryDayTrafficDataByDetectionSectionService_BulkCreateHistoryDayTrafficDataByDetectionSection_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_HistoryDayTrafficDataByDetectionSectionService_GetHistoryDayTrafficDataByDetectionSectionStatistics_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/pb.HistoryDayTrafficDataByDetectionSectionService/GetHistoryDayTrafficDataByDetectionSectionStatistics", runtime.WithHTTPPathPattern("/api/v1/traffic/history_day/detection_section/statistics"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_HistoryDayTrafficDataByDetectionSectionService_GetHistoryDayTrafficDataByDetectionSectionStatistics_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryDayTrafficDataByDetectionSectionService_GetHistoryDayTrafficDataByDetectionSectionStatistics_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_HistoryDayTrafficDataByDetectionSectionService_ListHistoryDayTrafficDataByDetectionSectionDaily_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/pb.HistoryDayTrafficDataByDetectionSectionService/ListHistoryDayTrafficDataByDetectionSectionDaily", runtime.WithHTTPPathPattern("/api/v1/traffic/history_day/detection_section/daily"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_HistoryDayTrafficDataByDetectionSectionService_ListHistoryDayTrafficDataByDetectionSectionDaily_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryDayTrafficDataByDetectionSectionService_ListHistoryDayTrafficDataByDetectionSectionDaily_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_HistoryDayTrafficDataByDetectionSectionService_DownloadHistoryDayTrafficDataByDetectionSection_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/pb.HistoryDayTrafficDataByDetectionSectionService/DownloadHistoryDayTrafficDataByDetectionSection", runtime.WithHTTPPathPattern("/api/v1/traffic/history_day/detection_section/download"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_HistoryDayTrafficDataByDetectionSectionService_DownloadHistoryDayTrafficDataByDetectionSection_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryDayTrafficDataByDetectionSectionService_DownloadHistoryDayTrafficDataByDetectionSection_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_HistoryDayTrafficDataByDetectionSectionService_ListHistoryDayTrafficDataByDetectionSection_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 2, 4, 2, 5}, []string{"api", "v1", "traffic", "history_day", "detection_section", "list"}, ""))

	pattern_HistoryDayTrafficDataByDetectionSectionService_GetHistoryDayTrafficDataByDetectionSection_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 2, 4, 2, 5}, []string{"api", "v1", "traffic", "history_day", "detection_section", "single"}, ""))

	pattern_HistoryDayTrafficDataByDetectionSectionService_CreateHistoryDayTrafficDataByDetectionSection_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 2, 4}, []string{"api", "v1", "traffic", "history_day", "detection_section"}, ""))

	pattern_HistoryDayTrafficDataByDetectionSectionService_UpdateHistoryDayTrafficDataByDetectionSection_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 2, 4}, []string{"api", "v1", "traffic", "history_day", "detection_section"}, ""))

	pattern_HistoryDayTrafficDataByDetectionSectionService_DeleteHistoryDayTrafficDataByDetectionSection_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 2, 4}, []string{"api", "v1", "traffic", "history_day", "detection_section"}, ""))

	pattern_HistoryDayTrafficDataByDetectionSectionService_BulkCreateHistoryDayTrafficDataByDetectionSection_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 2, 4, 2, 5}, []string{"api", "v1", "traffic", "history_day", "detection_section", "bulk"}, ""))

	pattern_HistoryDayTrafficDataByDetectionSectionService_GetHistoryDayTrafficDataByDetectionSectionStatistics_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 2, 4, 2, 5}, []string{"api", "v1", "traffic", "history_day", "detection_section", "statistics"}, ""))

	pattern_HistoryDayTrafficDataByDetectionSectionService_ListHistoryDayTrafficDataByDetectionSectionDaily_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 2, 4, 2, 5}, []string{"api", "v1", "traffic", "history_day", "detection_section", "daily"}, ""))

	pattern_HistoryDayTrafficDataByDetectionSectionService_DownloadHistoryDayTrafficDataByDetectionSection_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 2, 4, 2, 5}, []string{"api", "v1", "traffic", "history_day", "detection_section", "download"}, ""))
)

var (
	forward_HistoryDayTrafficDataByDetectionSectionService_ListHistoryDayTrafficDataByDetectionSection_0 = runtime.ForwardResponseMessage

	forward_HistoryDayTrafficDataByDetectionSectionService_GetHistoryDayTrafficDataByDetectionSection_0 = runtime.ForwardResponseMessage

	forward_HistoryDayTrafficDataByDetectionSectionService_CreateHistoryDayTrafficDataByDetectionSection_0 = runtime.ForwardResponseMessage

	forward_HistoryDayTrafficDataByDetectionSectionService_UpdateHistoryDayTrafficDataByDetectionSection_0 = runtime.ForwardResponseMessage

	forward_HistoryDayTrafficDataByDetectionSectionService_DeleteHistoryDayTrafficDataByDetectionSection_0 = runtime.ForwardResponseMessage

	forward_HistoryDayTrafficDataByDetectionSectionService_BulkCreateHistoryDayTrafficDataByDetectionSection_0 = runtime.ForwardResponseMessage

	forward_HistoryDayTrafficDataByDetectionSectionService_GetHistoryDayTrafficDataByDetectionSectionStatistics_0 = runtime.ForwardResponseMessage

	forward_HistoryDayTrafficDataByDetectionSectionService_ListHistoryDayTrafficDataByDetectionSectionDaily_0 = runtime.ForwardResponseMessage

	forward_HistoryDayTrafficDataByDetectionSectionService_DownloadHistoryDayTrafficDataByDetectionSection_0 = runtime.ForwardResponseMessage
)
