// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: services/history_day_traffic_data_detection_section.service.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListHistoryDayTrafficDataByDetectionSectionResponse struct {
	state                                   protoimpl.MessageState                  `protogen:"open.v1"`
	HistoryDayTrafficDataByDetectionSection []*HistoryTrafficDataByDetectionSection `protobuf:"bytes,1,rep,name=history_day_traffic_data_by_detection_section,json=historyDayTrafficDataByDetectionSection,proto3" json:"history_day_traffic_data_by_detection_section,omitempty"`
	TotalCount                              uint32                                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields                           protoimpl.UnknownFields
	sizeCache                               protoimpl.SizeCache
}

func (x *ListHistoryDayTrafficDataByDetectionSectionResponse) Reset() {
	*x = ListHistoryDayTrafficDataByDetectionSectionResponse{}
	mi := &file_services_history_day_traffic_data_detection_section_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHistoryDayTrafficDataByDetectionSectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHistoryDayTrafficDataByDetectionSectionResponse) ProtoMessage() {}

func (x *ListHistoryDayTrafficDataByDetectionSectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_history_day_traffic_data_detection_section_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHistoryDayTrafficDataByDetectionSectionResponse.ProtoReflect.Descriptor instead.
func (*ListHistoryDayTrafficDataByDetectionSectionResponse) Descriptor() ([]byte, []int) {
	return file_services_history_day_traffic_data_detection_section_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListHistoryDayTrafficDataByDetectionSectionResponse) GetHistoryDayTrafficDataByDetectionSection() []*HistoryTrafficDataByDetectionSection {
	if x != nil {
		return x.HistoryDayTrafficDataByDetectionSection
	}
	return nil
}

func (x *ListHistoryDayTrafficDataByDetectionSectionResponse) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetHistoryDayTrafficDataByDetectionSectionResponse struct {
	state                                   protoimpl.MessageState                  `protogen:"open.v1"`
	HistoryDayTrafficDataByDetectionSection []*HistoryTrafficDataByDetectionSection `protobuf:"bytes,1,rep,name=history_day_traffic_data_by_detection_section,json=historyDayTrafficDataByDetectionSection,proto3" json:"history_day_traffic_data_by_detection_section,omitempty"`
	TotalCount                              uint32                                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields                           protoimpl.UnknownFields
	sizeCache                               protoimpl.SizeCache
}

func (x *GetHistoryDayTrafficDataByDetectionSectionResponse) Reset() {
	*x = GetHistoryDayTrafficDataByDetectionSectionResponse{}
	mi := &file_services_history_day_traffic_data_detection_section_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryDayTrafficDataByDetectionSectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryDayTrafficDataByDetectionSectionResponse) ProtoMessage() {}

func (x *GetHistoryDayTrafficDataByDetectionSectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_history_day_traffic_data_detection_section_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryDayTrafficDataByDetectionSectionResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryDayTrafficDataByDetectionSectionResponse) Descriptor() ([]byte, []int) {
	return file_services_history_day_traffic_data_detection_section_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetHistoryDayTrafficDataByDetectionSectionResponse) GetHistoryDayTrafficDataByDetectionSection() []*HistoryTrafficDataByDetectionSection {
	if x != nil {
		return x.HistoryDayTrafficDataByDetectionSection
	}
	return nil
}

func (x *GetHistoryDayTrafficDataByDetectionSectionResponse) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type CreateHistoryDayTrafficDataByDetectionSectionRequest struct {
	state                                   protoimpl.MessageState                `protogen:"open.v1"`
	HistoryDayTrafficDataByDetectionSection *HistoryTrafficDataByDetectionSection `protobuf:"bytes,1,opt,name=history_day_traffic_data_by_detection_section,json=historyDayTrafficDataByDetectionSection,proto3" json:"history_day_traffic_data_by_detection_section,omitempty"`
	unknownFields                           protoimpl.UnknownFields
	sizeCache                               protoimpl.SizeCache
}

func (x *CreateHistoryDayTrafficDataByDetectionSectionRequest) Reset() {
	*x = CreateHistoryDayTrafficDataByDetectionSectionRequest{}
	mi := &file_services_history_day_traffic_data_detection_section_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHistoryDayTrafficDataByDetectionSectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHistoryDayTrafficDataByDetectionSectionRequest) ProtoMessage() {}

func (x *CreateHistoryDayTrafficDataByDetectionSectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_history_day_traffic_data_detection_section_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHistoryDayTrafficDataByDetectionSectionRequest.ProtoReflect.Descriptor instead.
func (*CreateHistoryDayTrafficDataByDetectionSectionRequest) Descriptor() ([]byte, []int) {
	return file_services_history_day_traffic_data_detection_section_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateHistoryDayTrafficDataByDetectionSectionRequest) GetHistoryDayTrafficDataByDetectionSection() *HistoryTrafficDataByDetectionSection {
	if x != nil {
		return x.HistoryDayTrafficDataByDetectionSection
	}
	return nil
}

type CreateHistoryDayTrafficDataByDetectionSectionResponse struct {
	state                                   protoimpl.MessageState                `protogen:"open.v1"`
	HistoryDayTrafficDataByDetectionSection *HistoryTrafficDataByDetectionSection `protobuf:"bytes,1,opt,name=history_day_traffic_data_by_detection_section,json=historyDayTrafficDataByDetectionSection,proto3" json:"history_day_traffic_data_by_detection_section,omitempty"`
	unknownFields                           protoimpl.UnknownFields
	sizeCache                               protoimpl.SizeCache
}

func (x *CreateHistoryDayTrafficDataByDetectionSectionResponse) Reset() {
	*x = CreateHistoryDayTrafficDataByDetectionSectionResponse{}
	mi := &file_services_history_day_traffic_data_detection_section_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHistoryDayTrafficDataByDetectionSectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHistoryDayTrafficDataByDetectionSectionResponse) ProtoMessage() {}

func (x *CreateHistoryDayTrafficDataByDetectionSectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_history_day_traffic_data_detection_section_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHistoryDayTrafficDataByDetectionSectionResponse.ProtoReflect.Descriptor instead.
func (*CreateHistoryDayTrafficDataByDetectionSectionResponse) Descriptor() ([]byte, []int) {
	return file_services_history_day_traffic_data_detection_section_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateHistoryDayTrafficDataByDetectionSectionResponse) GetHistoryDayTrafficDataByDetectionSection() *HistoryTrafficDataByDetectionSection {
	if x != nil {
		return x.HistoryDayTrafficDataByDetectionSection
	}
	return nil
}

type UpdateHistoryDayTrafficDataByDetectionSectionRequest struct {
	state                                   protoimpl.MessageState                `protogen:"open.v1"`
	HistoryDayTrafficDataByDetectionSection *HistoryTrafficDataByDetectionSection `protobuf:"bytes,1,opt,name=history_day_traffic_data_by_detection_section,json=historyDayTrafficDataByDetectionSection,proto3" json:"history_day_traffic_data_by_detection_section,omitempty"`
	unknownFields                           protoimpl.UnknownFields
	sizeCache                               protoimpl.SizeCache
}

func (x *UpdateHistoryDayTrafficDataByDetectionSectionRequest) Reset() {
	*x = UpdateHistoryDayTrafficDataByDetectionSectionRequest{}
	mi := &file_services_history_day_traffic_data_detection_section_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHistoryDayTrafficDataByDetectionSectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHistoryDayTrafficDataByDetectionSectionRequest) ProtoMessage() {}

func (x *UpdateHistoryDayTrafficDataByDetectionSectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_history_day_traffic_data_detection_section_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHistoryDayTrafficDataByDetectionSectionRequest.ProtoReflect.Descriptor instead.
func (*UpdateHistoryDayTrafficDataByDetectionSectionRequest) Descriptor() ([]byte, []int) {
	return file_services_history_day_traffic_data_detection_section_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateHistoryDayTrafficDataByDetectionSectionRequest) GetHistoryDayTrafficDataByDetectionSection() *HistoryTrafficDataByDetectionSection {
	if x != nil {
		return x.HistoryDayTrafficDataByDetectionSection
	}
	return nil
}

type UpdateHistoryDayTrafficDataByDetectionSectionResponse struct {
	state                                   protoimpl.MessageState                `protogen:"open.v1"`
	HistoryDayTrafficDataByDetectionSection *HistoryTrafficDataByDetectionSection `protobuf:"bytes,1,opt,name=history_day_traffic_data_by_detection_section,json=historyDayTrafficDataByDetectionSection,proto3" json:"history_day_traffic_data_by_detection_section,omitempty"`
	unknownFields                           protoimpl.UnknownFields
	sizeCache                               protoimpl.SizeCache
}

func (x *UpdateHistoryDayTrafficDataByDetectionSectionResponse) Reset() {
	*x = UpdateHistoryDayTrafficDataByDetectionSectionResponse{}
	mi := &file_services_history_day_traffic_data_detection_section_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHistoryDayTrafficDataByDetectionSectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHistoryDayTrafficDataByDetectionSectionResponse) ProtoMessage() {}

func (x *UpdateHistoryDayTrafficDataByDetectionSectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_history_day_traffic_data_detection_section_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHistoryDayTrafficDataByDetectionSectionResponse.ProtoReflect.Descriptor instead.
func (*UpdateHistoryDayTrafficDataByDetectionSectionResponse) Descriptor() ([]byte, []int) {
	return file_services_history_day_traffic_data_detection_section_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateHistoryDayTrafficDataByDetectionSectionResponse) GetHistoryDayTrafficDataByDetectionSection() *HistoryTrafficDataByDetectionSection {
	if x != nil {
		return x.HistoryDayTrafficDataByDetectionSection
	}
	return nil
}

type ListHistoryDayTrafficDataByDetectionSectionDailyResponse struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	DailyStats    []*HistoryTrafficDataByDetectionSection `protobuf:"bytes,1,rep,name=daily_stats,json=dailyStats,proto3" json:"daily_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHistoryDayTrafficDataByDetectionSectionDailyResponse) Reset() {
	*x = ListHistoryDayTrafficDataByDetectionSectionDailyResponse{}
	mi := &file_services_history_day_traffic_data_detection_section_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHistoryDayTrafficDataByDetectionSectionDailyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHistoryDayTrafficDataByDetectionSectionDailyResponse) ProtoMessage() {}

func (x *ListHistoryDayTrafficDataByDetectionSectionDailyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_history_day_traffic_data_detection_section_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHistoryDayTrafficDataByDetectionSectionDailyResponse.ProtoReflect.Descriptor instead.
func (*ListHistoryDayTrafficDataByDetectionSectionDailyResponse) Descriptor() ([]byte, []int) {
	return file_services_history_day_traffic_data_detection_section_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListHistoryDayTrafficDataByDetectionSectionDailyResponse) GetDailyStats() []*HistoryTrafficDataByDetectionSection {
	if x != nil {
		return x.DailyStats
	}
	return nil
}

var File_services_history_day_traffic_data_detection_section_service_proto protoreflect.FileDescriptor

const file_services_history_day_traffic_data_detection_section_service_proto_rawDesc = "" +
	"\n" +
	"Aservices/history_day_traffic_data_detection_section.service.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a1dtos/history_traffic_data_detection_section.proto\x1a\x1bdtos/traffic_requests.proto\x1a\x1cdtos/traffic_responses.proto\"\xe1\x01\n" +
	"3ListHistoryDayTrafficDataByDetectionSectionResponse\x12\x88\x01\n" +
	"-history_day_traffic_data_by_detection_section\x18\x01 \x03(\v2(.pb.HistoryTrafficDataByDetectionSectionR'historyDayTrafficDataByDetectionSection\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\rR\n" +
	"totalCount\"\xe0\x01\n" +
	"2GetHistoryDayTrafficDataByDetectionSectionResponse\x12\x88\x01\n" +
	"-history_day_traffic_data_by_detection_section\x18\x01 \x03(\v2(.pb.HistoryTrafficDataByDetectionSectionR'historyDayTrafficDataByDetectionSection\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\rR\n" +
	"totalCount\"\xc1\x01\n" +
	"4CreateHistoryDayTrafficDataByDetectionSectionRequest\x12\x88\x01\n" +
	"-history_day_traffic_data_by_detection_section\x18\x01 \x01(\v2(.pb.HistoryTrafficDataByDetectionSectionR'historyDayTrafficDataByDetectionSection\"\xc2\x01\n" +
	"5CreateHistoryDayTrafficDataByDetectionSectionResponse\x12\x88\x01\n" +
	"-history_day_traffic_data_by_detection_section\x18\x01 \x01(\v2(.pb.HistoryTrafficDataByDetectionSectionR'historyDayTrafficDataByDetectionSection\"\xc1\x01\n" +
	"4UpdateHistoryDayTrafficDataByDetectionSectionRequest\x12\x88\x01\n" +
	"-history_day_traffic_data_by_detection_section\x18\x01 \x01(\v2(.pb.HistoryTrafficDataByDetectionSectionR'historyDayTrafficDataByDetectionSection\"\xc2\x01\n" +
	"5UpdateHistoryDayTrafficDataByDetectionSectionResponse\x12\x88\x01\n" +
	"-history_day_traffic_data_by_detection_section\x18\x01 \x01(\v2(.pb.HistoryTrafficDataByDetectionSectionR'historyDayTrafficDataByDetectionSection\"\x85\x01\n" +
	"8ListHistoryDayTrafficDataByDetectionSectionDailyResponse\x12I\n" +
	"\vdaily_stats\x18\x01 \x03(\v2(.pb.HistoryTrafficDataByDetectionSectionR\n" +
	"dailyStats2\xc8\x10\n" +
	".HistoryDayTrafficDataByDetectionSectionService\x12\xe1\x01\n" +
	"+ListHistoryDayTrafficDataByDetectionSection\x12,.pb.ListTrafficDataByDetectionSectionRequest\x1a7.pb.ListHistoryDayTrafficDataByDetectionSectionResponse\"K\x92A\x0eb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x024\x122/api/v1/traffic/history_day/detection_section/list\x12\xe0\x01\n" +
	"*GetHistoryDayTrafficDataByDetectionSection\x12+.pb.GetTrafficDataByDetectionSectionRequest\x1a6.pb.GetHistoryDayTrafficDataByDetectionSectionResponse\"M\x92A\x0eb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x026\x124/api/v1/traffic/history_day/detection_section/single\x12\xef\x01\n" +
	"-CreateHistoryDayTrafficDataByDetectionSection\x128.pb.CreateHistoryDayTrafficDataByDetectionSectionRequest\x1a9.pb.CreateHistoryDayTrafficDataByDetectionSectionResponse\"I\x92A\x0eb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x022:\x01*\"-/api/v1/traffic/history_day/detection_section\x12\xef\x01\n" +
	"-UpdateHistoryDayTrafficDataByDetectionSection\x128.pb.UpdateHistoryDayTrafficDataByDetectionSectionRequest\x1a9.pb.UpdateHistoryDayTrafficDataByDetectionSectionResponse\"I\x92A\x0eb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x022:\x01*2-/api/v1/traffic/history_day/detection_section\x12\xbf\x01\n" +
	"-DeleteHistoryDayTrafficDataByDetectionSection\x12..pb.DeleteTrafficDataByDetectionSectionRequest\x1a\x16.google.protobuf.Empty\"F\x92A\x0eb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x02/*-/api/v1/traffic/history_day/detection_section\x12\xec\x01\n" +
	"1BulkCreateHistoryDayTrafficDataByDetectionSection\x122.pb.BulkCreateTrafficDataByDetectionSectionRequest\x1a3.pb.BulkCreateTrafficDataByDetectionSectionResponse\"N\x92A\x0eb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x027:\x01*\"2/api/v1/traffic/history_day/detection_section/bulk\x12\xf8\x01\n" +
	"4GetHistoryDayTrafficDataByDetectionSectionStatistics\x125.pb.GetTrafficDataByDetectionSectionStatisticsRequest\x1a6.pb.GetTrafficDataByDetectionSectionStatisticsResponse\"Q\x92A\x0eb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x02:\x128/api/v1/traffic/history_day/detection_section/statistics\x12\xf1\x01\n" +
	"0ListHistoryDayTrafficDataByDetectionSectionDaily\x121.pb.ListTrafficDataByDetectionSectionDailyRequest\x1a<.pb.ListHistoryDayTrafficDataByDetectionSectionDailyResponse\"L\x92A\x0eb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x025\x123/api/v1/traffic/history_day/detection_section/daily\x12\xca\x01\n" +
	"/DownloadHistoryDayTrafficDataByDetectionSection\x120.pb.DownloadTrafficDataByDetectionSectionRequest\x1a\x14.pb.DownloadResponse\"O\x92A\x0eb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x028\x126/api/v1/traffic/history_day/detection_section/downloadB~\x92AiZY\n" +
	"W\n" +
	"\x06bearer\x12M\b\x02\x128Authentication token, prefixed by Bearer: Bearer <token>\x1a\rAuthorization \x02b\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00Z\x10internal/data/pbb\x06proto3"

var (
	file_services_history_day_traffic_data_detection_section_service_proto_rawDescOnce sync.Once
	file_services_history_day_traffic_data_detection_section_service_proto_rawDescData []byte
)

func file_services_history_day_traffic_data_detection_section_service_proto_rawDescGZIP() []byte {
	file_services_history_day_traffic_data_detection_section_service_proto_rawDescOnce.Do(func() {
		file_services_history_day_traffic_data_detection_section_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_history_day_traffic_data_detection_section_service_proto_rawDesc), len(file_services_history_day_traffic_data_detection_section_service_proto_rawDesc)))
	})
	return file_services_history_day_traffic_data_detection_section_service_proto_rawDescData
}

var file_services_history_day_traffic_data_detection_section_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_services_history_day_traffic_data_detection_section_service_proto_goTypes = []any{
	(*ListHistoryDayTrafficDataByDetectionSectionResponse)(nil),      // 0: pb.ListHistoryDayTrafficDataByDetectionSectionResponse
	(*GetHistoryDayTrafficDataByDetectionSectionResponse)(nil),       // 1: pb.GetHistoryDayTrafficDataByDetectionSectionResponse
	(*CreateHistoryDayTrafficDataByDetectionSectionRequest)(nil),     // 2: pb.CreateHistoryDayTrafficDataByDetectionSectionRequest
	(*CreateHistoryDayTrafficDataByDetectionSectionResponse)(nil),    // 3: pb.CreateHistoryDayTrafficDataByDetectionSectionResponse
	(*UpdateHistoryDayTrafficDataByDetectionSectionRequest)(nil),     // 4: pb.UpdateHistoryDayTrafficDataByDetectionSectionRequest
	(*UpdateHistoryDayTrafficDataByDetectionSectionResponse)(nil),    // 5: pb.UpdateHistoryDayTrafficDataByDetectionSectionResponse
	(*ListHistoryDayTrafficDataByDetectionSectionDailyResponse)(nil), // 6: pb.ListHistoryDayTrafficDataByDetectionSectionDailyResponse
	(*HistoryTrafficDataByDetectionSection)(nil),                     // 7: pb.HistoryTrafficDataByDetectionSection
	(*ListTrafficDataByDetectionSectionRequest)(nil),                 // 8: pb.ListTrafficDataByDetectionSectionRequest
	(*GetTrafficDataByDetectionSectionRequest)(nil),                  // 9: pb.GetTrafficDataByDetectionSectionRequest
	(*DeleteTrafficDataByDetectionSectionRequest)(nil),               // 10: pb.DeleteTrafficDataByDetectionSectionRequest
	(*BulkCreateTrafficDataByDetectionSectionRequest)(nil),           // 11: pb.BulkCreateTrafficDataByDetectionSectionRequest
	(*GetTrafficDataByDetectionSectionStatisticsRequest)(nil),        // 12: pb.GetTrafficDataByDetectionSectionStatisticsRequest
	(*ListTrafficDataByDetectionSectionDailyRequest)(nil),            // 13: pb.ListTrafficDataByDetectionSectionDailyRequest
	(*DownloadTrafficDataByDetectionSectionRequest)(nil),             // 14: pb.DownloadTrafficDataByDetectionSectionRequest
	(*emptypb.Empty)(nil), // 15: google.protobuf.Empty
	(*BulkCreateTrafficDataByDetectionSectionResponse)(nil),    // 16: pb.BulkCreateTrafficDataByDetectionSectionResponse
	(*GetTrafficDataByDetectionSectionStatisticsResponse)(nil), // 17: pb.GetTrafficDataByDetectionSectionStatisticsResponse
	(*DownloadResponse)(nil),                                   // 18: pb.DownloadResponse
}
var file_services_history_day_traffic_data_detection_section_service_proto_depIdxs = []int32{
	7,  // 0: pb.ListHistoryDayTrafficDataByDetectionSectionResponse.history_day_traffic_data_by_detection_section:type_name -> pb.HistoryTrafficDataByDetectionSection
	7,  // 1: pb.GetHistoryDayTrafficDataByDetectionSectionResponse.history_day_traffic_data_by_detection_section:type_name -> pb.HistoryTrafficDataByDetectionSection
	7,  // 2: pb.CreateHistoryDayTrafficDataByDetectionSectionRequest.history_day_traffic_data_by_detection_section:type_name -> pb.HistoryTrafficDataByDetectionSection
	7,  // 3: pb.CreateHistoryDayTrafficDataByDetectionSectionResponse.history_day_traffic_data_by_detection_section:type_name -> pb.HistoryTrafficDataByDetectionSection
	7,  // 4: pb.UpdateHistoryDayTrafficDataByDetectionSectionRequest.history_day_traffic_data_by_detection_section:type_name -> pb.HistoryTrafficDataByDetectionSection
	7,  // 5: pb.UpdateHistoryDayTrafficDataByDetectionSectionResponse.history_day_traffic_data_by_detection_section:type_name -> pb.HistoryTrafficDataByDetectionSection
	7,  // 6: pb.ListHistoryDayTrafficDataByDetectionSectionDailyResponse.daily_stats:type_name -> pb.HistoryTrafficDataByDetectionSection
	8,  // 7: pb.HistoryDayTrafficDataByDetectionSectionService.ListHistoryDayTrafficDataByDetectionSection:input_type -> pb.ListTrafficDataByDetectionSectionRequest
	9,  // 8: pb.HistoryDayTrafficDataByDetectionSectionService.GetHistoryDayTrafficDataByDetectionSection:input_type -> pb.GetTrafficDataByDetectionSectionRequest
	2,  // 9: pb.HistoryDayTrafficDataByDetectionSectionService.CreateHistoryDayTrafficDataByDetectionSection:input_type -> pb.CreateHistoryDayTrafficDataByDetectionSectionRequest
	4,  // 10: pb.HistoryDayTrafficDataByDetectionSectionService.UpdateHistoryDayTrafficDataByDetectionSection:input_type -> pb.UpdateHistoryDayTrafficDataByDetectionSectionRequest
	10, // 11: pb.HistoryDayTrafficDataByDetectionSectionService.DeleteHistoryDayTrafficDataByDetectionSection:input_type -> pb.DeleteTrafficDataByDetectionSectionRequest
	11, // 12: pb.HistoryDayTrafficDataByDetectionSectionService.BulkCreateHistoryDayTrafficDataByDetectionSection:input_type -> pb.BulkCreateTrafficDataByDetectionSectionRequest
	12, // 13: pb.HistoryDayTrafficDataByDetectionSectionService.GetHistoryDayTrafficDataByDetectionSectionStatistics:input_type -> pb.GetTrafficDataByDetectionSectionStatisticsRequest
	13, // 14: pb.HistoryDayTrafficDataByDetectionSectionService.ListHistoryDayTrafficDataByDetectionSectionDaily:input_type -> pb.ListTrafficDataByDetectionSectionDailyRequest
	14, // 15: pb.HistoryDayTrafficDataByDetectionSectionService.DownloadHistoryDayTrafficDataByDetectionSection:input_type -> pb.DownloadTrafficDataByDetectionSectionRequest
	0,  // 16: pb.HistoryDayTrafficDataByDetectionSectionService.ListHistoryDayTrafficDataByDetectionSection:output_type -> pb.ListHistoryDayTrafficDataByDetectionSectionResponse
	1,  // 17: pb.HistoryDayTrafficDataByDetectionSectionService.GetHistoryDayTrafficDataByDetectionSection:output_type -> pb.GetHistoryDayTrafficDataByDetectionSectionResponse
	3,  // 18: pb.HistoryDayTrafficDataByDetectionSectionService.CreateHistoryDayTrafficDataByDetectionSection:output_type -> pb.CreateHistoryDayTrafficDataByDetectionSectionResponse
	5,  // 19: pb.HistoryDayTrafficDataByDetectionSectionService.UpdateHistoryDayTrafficDataByDetectionSection:output_type -> pb.UpdateHistoryDayTrafficDataByDetectionSectionResponse
	15, // 20: pb.HistoryDayTrafficDataByDetectionSectionService.DeleteHistoryDayTrafficDataByDetectionSection:output_type -> google.protobuf.Empty
	16, // 21: pb.HistoryDayTrafficDataByDetectionSectionService.BulkCreateHistoryDayTrafficDataByDetectionSection:output_type -> pb.BulkCreateTrafficDataByDetectionSectionResponse
	17, // 22: pb.HistoryDayTrafficDataByDetectionSectionService.GetHistoryDayTrafficDataByDetectionSectionStatistics:output_type -> pb.GetTrafficDataByDetectionSectionStatisticsResponse
	6,  // 23: pb.HistoryDayTrafficDataByDetectionSectionService.ListHistoryDayTrafficDataByDetectionSectionDaily:output_type -> pb.ListHistoryDayTrafficDataByDetectionSectionDailyResponse
	18, // 24: pb.HistoryDayTrafficDataByDetectionSectionService.DownloadHistoryDayTrafficDataByDetectionSection:output_type -> pb.DownloadResponse
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_services_history_day_traffic_data_detection_section_service_proto_init() }
func file_services_history_day_traffic_data_detection_section_service_proto_init() {
	if File_services_history_day_traffic_data_detection_section_service_proto != nil {
		return
	}
	file_dtos_history_traffic_data_detection_section_proto_init()
	file_dtos_traffic_requests_proto_init()
	file_dtos_traffic_responses_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_history_day_traffic_data_detection_section_service_proto_rawDesc), len(file_services_history_day_traffic_data_detection_section_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_history_day_traffic_data_detection_section_service_proto_goTypes,
		DependencyIndexes: file_services_history_day_traffic_data_detection_section_service_proto_depIdxs,
		MessageInfos:      file_services_history_day_traffic_data_detection_section_service_proto_msgTypes,
	}.Build()
	File_services_history_day_traffic_data_detection_section_service_proto = out.File
	file_services_history_day_traffic_data_detection_section_service_proto_goTypes = nil
	file_services_history_day_traffic_data_detection_section_service_proto_depIdxs = nil
}
