// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: services/history_hour_traffic_data_detection_point.service.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListHistoryHourTrafficDataByDetectionPointResponse struct {
	state                                   protoimpl.MessageState                    `protogen:"open.v1"`
	HistoryHourTrafficDataByDetectionPoints []*HistoryHourTrafficDataByDetectionPoint `protobuf:"bytes,1,rep,name=history_hour_traffic_data_by_detection_points,json=historyHourTrafficDataByDetectionPoints,proto3" json:"history_hour_traffic_data_by_detection_points,omitempty"`
	TotalCount                              uint32                                    `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields                           protoimpl.UnknownFields
	sizeCache                               protoimpl.SizeCache
}

func (x *ListHistoryHourTrafficDataByDetectionPointResponse) Reset() {
	*x = ListHistoryHourTrafficDataByDetectionPointResponse{}
	mi := &file_services_history_hour_traffic_data_detection_point_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHistoryHourTrafficDataByDetectionPointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHistoryHourTrafficDataByDetectionPointResponse) ProtoMessage() {}

func (x *ListHistoryHourTrafficDataByDetectionPointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_history_hour_traffic_data_detection_point_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHistoryHourTrafficDataByDetectionPointResponse.ProtoReflect.Descriptor instead.
func (*ListHistoryHourTrafficDataByDetectionPointResponse) Descriptor() ([]byte, []int) {
	return file_services_history_hour_traffic_data_detection_point_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListHistoryHourTrafficDataByDetectionPointResponse) GetHistoryHourTrafficDataByDetectionPoints() []*HistoryHourTrafficDataByDetectionPoint {
	if x != nil {
		return x.HistoryHourTrafficDataByDetectionPoints
	}
	return nil
}

func (x *ListHistoryHourTrafficDataByDetectionPointResponse) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetHistoryHourTrafficDataByDetectionPointResponse struct {
	state                                  protoimpl.MessageState                    `protogen:"open.v1"`
	HistoryHourTrafficDataByDetectionPoint []*HistoryHourTrafficDataByDetectionPoint `protobuf:"bytes,1,rep,name=history_hour_traffic_data_by_detection_point,json=historyHourTrafficDataByDetectionPoint,proto3" json:"history_hour_traffic_data_by_detection_point,omitempty"`
	TotalCount                             uint32                                    `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields                          protoimpl.UnknownFields
	sizeCache                              protoimpl.SizeCache
}

func (x *GetHistoryHourTrafficDataByDetectionPointResponse) Reset() {
	*x = GetHistoryHourTrafficDataByDetectionPointResponse{}
	mi := &file_services_history_hour_traffic_data_detection_point_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryHourTrafficDataByDetectionPointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryHourTrafficDataByDetectionPointResponse) ProtoMessage() {}

func (x *GetHistoryHourTrafficDataByDetectionPointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_history_hour_traffic_data_detection_point_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryHourTrafficDataByDetectionPointResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryHourTrafficDataByDetectionPointResponse) Descriptor() ([]byte, []int) {
	return file_services_history_hour_traffic_data_detection_point_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetHistoryHourTrafficDataByDetectionPointResponse) GetHistoryHourTrafficDataByDetectionPoint() []*HistoryHourTrafficDataByDetectionPoint {
	if x != nil {
		return x.HistoryHourTrafficDataByDetectionPoint
	}
	return nil
}

func (x *GetHistoryHourTrafficDataByDetectionPointResponse) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type CreateHistoryHourTrafficDataByDetectionPointRequest struct {
	state                                  protoimpl.MessageState                  `protogen:"open.v1"`
	HistoryHourTrafficDataByDetectionPoint *HistoryHourTrafficDataByDetectionPoint `protobuf:"bytes,1,opt,name=history_hour_traffic_data_by_detection_point,json=historyHourTrafficDataByDetectionPoint,proto3" json:"history_hour_traffic_data_by_detection_point,omitempty"`
	unknownFields                          protoimpl.UnknownFields
	sizeCache                              protoimpl.SizeCache
}

func (x *CreateHistoryHourTrafficDataByDetectionPointRequest) Reset() {
	*x = CreateHistoryHourTrafficDataByDetectionPointRequest{}
	mi := &file_services_history_hour_traffic_data_detection_point_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHistoryHourTrafficDataByDetectionPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHistoryHourTrafficDataByDetectionPointRequest) ProtoMessage() {}

func (x *CreateHistoryHourTrafficDataByDetectionPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_history_hour_traffic_data_detection_point_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHistoryHourTrafficDataByDetectionPointRequest.ProtoReflect.Descriptor instead.
func (*CreateHistoryHourTrafficDataByDetectionPointRequest) Descriptor() ([]byte, []int) {
	return file_services_history_hour_traffic_data_detection_point_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateHistoryHourTrafficDataByDetectionPointRequest) GetHistoryHourTrafficDataByDetectionPoint() *HistoryHourTrafficDataByDetectionPoint {
	if x != nil {
		return x.HistoryHourTrafficDataByDetectionPoint
	}
	return nil
}

type CreateHistoryHourTrafficDataByDetectionPointResponse struct {
	state                                  protoimpl.MessageState                  `protogen:"open.v1"`
	HistoryHourTrafficDataByDetectionPoint *HistoryHourTrafficDataByDetectionPoint `protobuf:"bytes,1,opt,name=history_hour_traffic_data_by_detection_point,json=historyHourTrafficDataByDetectionPoint,proto3" json:"history_hour_traffic_data_by_detection_point,omitempty"`
	unknownFields                          protoimpl.UnknownFields
	sizeCache                              protoimpl.SizeCache
}

func (x *CreateHistoryHourTrafficDataByDetectionPointResponse) Reset() {
	*x = CreateHistoryHourTrafficDataByDetectionPointResponse{}
	mi := &file_services_history_hour_traffic_data_detection_point_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHistoryHourTrafficDataByDetectionPointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHistoryHourTrafficDataByDetectionPointResponse) ProtoMessage() {}

func (x *CreateHistoryHourTrafficDataByDetectionPointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_history_hour_traffic_data_detection_point_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHistoryHourTrafficDataByDetectionPointResponse.ProtoReflect.Descriptor instead.
func (*CreateHistoryHourTrafficDataByDetectionPointResponse) Descriptor() ([]byte, []int) {
	return file_services_history_hour_traffic_data_detection_point_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateHistoryHourTrafficDataByDetectionPointResponse) GetHistoryHourTrafficDataByDetectionPoint() *HistoryHourTrafficDataByDetectionPoint {
	if x != nil {
		return x.HistoryHourTrafficDataByDetectionPoint
	}
	return nil
}

type UpdateHistoryHourTrafficDataByDetectionPointRequest struct {
	state                                  protoimpl.MessageState                  `protogen:"open.v1"`
	HistoryHourTrafficDataByDetectionPoint *HistoryHourTrafficDataByDetectionPoint `protobuf:"bytes,1,opt,name=history_hour_traffic_data_by_detection_point,json=historyHourTrafficDataByDetectionPoint,proto3" json:"history_hour_traffic_data_by_detection_point,omitempty"`
	unknownFields                          protoimpl.UnknownFields
	sizeCache                              protoimpl.SizeCache
}

func (x *UpdateHistoryHourTrafficDataByDetectionPointRequest) Reset() {
	*x = UpdateHistoryHourTrafficDataByDetectionPointRequest{}
	mi := &file_services_history_hour_traffic_data_detection_point_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHistoryHourTrafficDataByDetectionPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHistoryHourTrafficDataByDetectionPointRequest) ProtoMessage() {}

func (x *UpdateHistoryHourTrafficDataByDetectionPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_history_hour_traffic_data_detection_point_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHistoryHourTrafficDataByDetectionPointRequest.ProtoReflect.Descriptor instead.
func (*UpdateHistoryHourTrafficDataByDetectionPointRequest) Descriptor() ([]byte, []int) {
	return file_services_history_hour_traffic_data_detection_point_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateHistoryHourTrafficDataByDetectionPointRequest) GetHistoryHourTrafficDataByDetectionPoint() *HistoryHourTrafficDataByDetectionPoint {
	if x != nil {
		return x.HistoryHourTrafficDataByDetectionPoint
	}
	return nil
}

type UpdateHistoryHourTrafficDataByDetectionPointResponse struct {
	state                                  protoimpl.MessageState                  `protogen:"open.v1"`
	HistoryHourTrafficDataByDetectionPoint *HistoryHourTrafficDataByDetectionPoint `protobuf:"bytes,1,opt,name=history_hour_traffic_data_by_detection_point,json=historyHourTrafficDataByDetectionPoint,proto3" json:"history_hour_traffic_data_by_detection_point,omitempty"`
	unknownFields                          protoimpl.UnknownFields
	sizeCache                              protoimpl.SizeCache
}

func (x *UpdateHistoryHourTrafficDataByDetectionPointResponse) Reset() {
	*x = UpdateHistoryHourTrafficDataByDetectionPointResponse{}
	mi := &file_services_history_hour_traffic_data_detection_point_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHistoryHourTrafficDataByDetectionPointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHistoryHourTrafficDataByDetectionPointResponse) ProtoMessage() {}

func (x *UpdateHistoryHourTrafficDataByDetectionPointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_history_hour_traffic_data_detection_point_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHistoryHourTrafficDataByDetectionPointResponse.ProtoReflect.Descriptor instead.
func (*UpdateHistoryHourTrafficDataByDetectionPointResponse) Descriptor() ([]byte, []int) {
	return file_services_history_hour_traffic_data_detection_point_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateHistoryHourTrafficDataByDetectionPointResponse) GetHistoryHourTrafficDataByDetectionPoint() *HistoryHourTrafficDataByDetectionPoint {
	if x != nil {
		return x.HistoryHourTrafficDataByDetectionPoint
	}
	return nil
}

type ListHistoryHourTrafficDataByDetectionPointDailyResponse struct {
	state         protoimpl.MessageState                    `protogen:"open.v1"`
	DailyStats    []*HistoryHourTrafficDataByDetectionPoint `protobuf:"bytes,1,rep,name=daily_stats,json=dailyStats,proto3" json:"daily_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHistoryHourTrafficDataByDetectionPointDailyResponse) Reset() {
	*x = ListHistoryHourTrafficDataByDetectionPointDailyResponse{}
	mi := &file_services_history_hour_traffic_data_detection_point_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHistoryHourTrafficDataByDetectionPointDailyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHistoryHourTrafficDataByDetectionPointDailyResponse) ProtoMessage() {}

func (x *ListHistoryHourTrafficDataByDetectionPointDailyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_history_hour_traffic_data_detection_point_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHistoryHourTrafficDataByDetectionPointDailyResponse.ProtoReflect.Descriptor instead.
func (*ListHistoryHourTrafficDataByDetectionPointDailyResponse) Descriptor() ([]byte, []int) {
	return file_services_history_hour_traffic_data_detection_point_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListHistoryHourTrafficDataByDetectionPointDailyResponse) GetDailyStats() []*HistoryHourTrafficDataByDetectionPoint {
	if x != nil {
		return x.DailyStats
	}
	return nil
}

var File_services_history_hour_traffic_data_detection_point_service_proto protoreflect.FileDescriptor

const file_services_history_hour_traffic_data_detection_point_service_proto_rawDesc = "" +
	"\n" +
	"@services/history_hour_traffic_data_detection_point.service.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a4dtos/history_hour_traffic_data_detection_point.proto\x1a\x1bdtos/traffic_requests.proto\x1a\x1cdtos/traffic_responses.proto\"\xe2\x01\n" +
	"2ListHistoryHourTrafficDataByDetectionPointResponse\x12\x8a\x01\n" +
	"-history_hour_traffic_data_by_detection_points\x18\x01 \x03(\v2*.pb.HistoryHourTrafficDataByDetectionPointR'historyHourTrafficDataByDetectionPoints\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\rR\n" +
	"totalCount\"\xdf\x01\n" +
	"1GetHistoryHourTrafficDataByDetectionPointResponse\x12\x88\x01\n" +
	",history_hour_traffic_data_by_detection_point\x18\x01 \x03(\v2*.pb.HistoryHourTrafficDataByDetectionPointR&historyHourTrafficDataByDetectionPoint\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\rR\n" +
	"totalCount\"\xc0\x01\n" +
	"3CreateHistoryHourTrafficDataByDetectionPointRequest\x12\x88\x01\n" +
	",history_hour_traffic_data_by_detection_point\x18\x01 \x01(\v2*.pb.HistoryHourTrafficDataByDetectionPointR&historyHourTrafficDataByDetectionPoint\"\xc1\x01\n" +
	"4CreateHistoryHourTrafficDataByDetectionPointResponse\x12\x88\x01\n" +
	",history_hour_traffic_data_by_detection_point\x18\x01 \x01(\v2*.pb.HistoryHourTrafficDataByDetectionPointR&historyHourTrafficDataByDetectionPoint\"\xc0\x01\n" +
	"3UpdateHistoryHourTrafficDataByDetectionPointRequest\x12\x88\x01\n" +
	",history_hour_traffic_data_by_detection_point\x18\x01 \x01(\v2*.pb.HistoryHourTrafficDataByDetectionPointR&historyHourTrafficDataByDetectionPoint\"\xc1\x01\n" +
	"4UpdateHistoryHourTrafficDataByDetectionPointResponse\x12\x88\x01\n" +
	",history_hour_traffic_data_by_detection_point\x18\x01 \x01(\v2*.pb.HistoryHourTrafficDataByDetectionPointR&historyHourTrafficDataByDetectionPoint\"\x86\x01\n" +
	"7ListHistoryHourTrafficDataByDetectionPointDailyResponse\x12K\n" +
	"\vdaily_stats\x18\x01 \x03(\v2*.pb.HistoryHourTrafficDataByDetectionPointR\n" +
	"dailyStats2\x9c\x10\n" +
	"-HistoryHourTrafficDataByDetectionPointService\x12\xdc\x01\n" +
	"*ListHistoryHourTrafficDataByDetectionPoint\x12*.pb.ListTrafficDataByDetectionPointRequest\x1a6.pb.ListHistoryHourTrafficDataByDetectionPointResponse\"J\x92A\x0eb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x023\x121/api/v1/traffic/history_hour/detection_point/list\x12\xdb\x01\n" +
	")GetHistoryHourTrafficDataByDetectionPoint\x12).pb.GetTrafficDataByDetectionPointRequest\x1a5.pb.GetHistoryHourTrafficDataByDetectionPointResponse\"L\x92A\x0eb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x025\x123/api/v1/traffic/history_hour/detection_point/single\x12\xeb\x01\n" +
	",CreateHistoryHourTrafficDataByDetectionPoint\x127.pb.CreateHistoryHourTrafficDataByDetectionPointRequest\x1a8.pb.CreateHistoryHourTrafficDataByDetectionPointResponse\"H\x92A\x0eb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x021:\x01*\",/api/v1/traffic/history_hour/detection_point\x12\xeb\x01\n" +
	",UpdateHistoryHourTrafficDataByDetectionPoint\x127.pb.UpdateHistoryHourTrafficDataByDetectionPointRequest\x1a8.pb.UpdateHistoryHourTrafficDataByDetectionPointResponse\"H\x92A\x0eb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x021:\x01*2,/api/v1/traffic/history_hour/detection_point\x12\xbb\x01\n" +
	",DeleteHistoryHourTrafficDataByDetectionPoint\x12,.pb.DeleteTrafficDataByDetectionPointRequest\x1a\x16.google.protobuf.Empty\"E\x92A\x0eb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x02.*,/api/v1/traffic/history_hour/detection_point\x12\xe6\x01\n" +
	"0BulkCreateHistoryHourTrafficDataByDetectionPoint\x120.pb.BulkCreateTrafficDataByDetectionPointRequest\x1a1.pb.BulkCreateTrafficDataByDetectionPointResponse\"M\x92A\x0eb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x026:\x01*\"1/api/v1/traffic/history_hour/detection_point/bulk\x12\xf2\x01\n" +
	"3GetHistoryHourTrafficDataByDetectionPointStatistics\x123.pb.GetTrafficDataByDetectionPointStatisticsRequest\x1a4.pb.GetTrafficDataByDetectionPointStatisticsResponse\"P\x92A\x0eb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x029\x127/api/v1/traffic/history_hour/detection_point/statistics\x12\xec\x01\n" +
	"/ListHistoryHourTrafficDataByDetectionPointDaily\x12/.pb.ListTrafficDataByDetectionPointDailyRequest\x1a;.pb.ListHistoryHourTrafficDataByDetectionPointDailyResponse\"K\x92A\x0eb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x024\x122/api/v1/traffic/history_hour/detection_point/daily\x12\xc6\x01\n" +
	".DownloadHistoryHourTrafficDataByDetectionPoint\x12..pb.DownloadTrafficDataByDetectionPointRequest\x1a\x14.pb.DownloadResponse\"N\x92A\x0eb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x027\x125/api/v1/traffic/history_hour/detection_point/downloadB~\x92AiZY\n" +
	"W\n" +
	"\x06bearer\x12M\b\x02\x128Authentication token, prefixed by Bearer: Bearer <token>\x1a\rAuthorization \x02b\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00Z\x10internal/data/pbb\x06proto3"

var (
	file_services_history_hour_traffic_data_detection_point_service_proto_rawDescOnce sync.Once
	file_services_history_hour_traffic_data_detection_point_service_proto_rawDescData []byte
)

func file_services_history_hour_traffic_data_detection_point_service_proto_rawDescGZIP() []byte {
	file_services_history_hour_traffic_data_detection_point_service_proto_rawDescOnce.Do(func() {
		file_services_history_hour_traffic_data_detection_point_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_history_hour_traffic_data_detection_point_service_proto_rawDesc), len(file_services_history_hour_traffic_data_detection_point_service_proto_rawDesc)))
	})
	return file_services_history_hour_traffic_data_detection_point_service_proto_rawDescData
}

var file_services_history_hour_traffic_data_detection_point_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_services_history_hour_traffic_data_detection_point_service_proto_goTypes = []any{
	(*ListHistoryHourTrafficDataByDetectionPointResponse)(nil),      // 0: pb.ListHistoryHourTrafficDataByDetectionPointResponse
	(*GetHistoryHourTrafficDataByDetectionPointResponse)(nil),       // 1: pb.GetHistoryHourTrafficDataByDetectionPointResponse
	(*CreateHistoryHourTrafficDataByDetectionPointRequest)(nil),     // 2: pb.CreateHistoryHourTrafficDataByDetectionPointRequest
	(*CreateHistoryHourTrafficDataByDetectionPointResponse)(nil),    // 3: pb.CreateHistoryHourTrafficDataByDetectionPointResponse
	(*UpdateHistoryHourTrafficDataByDetectionPointRequest)(nil),     // 4: pb.UpdateHistoryHourTrafficDataByDetectionPointRequest
	(*UpdateHistoryHourTrafficDataByDetectionPointResponse)(nil),    // 5: pb.UpdateHistoryHourTrafficDataByDetectionPointResponse
	(*ListHistoryHourTrafficDataByDetectionPointDailyResponse)(nil), // 6: pb.ListHistoryHourTrafficDataByDetectionPointDailyResponse
	(*HistoryHourTrafficDataByDetectionPoint)(nil),                  // 7: pb.HistoryHourTrafficDataByDetectionPoint
	(*ListTrafficDataByDetectionPointRequest)(nil),                  // 8: pb.ListTrafficDataByDetectionPointRequest
	(*GetTrafficDataByDetectionPointRequest)(nil),                   // 9: pb.GetTrafficDataByDetectionPointRequest
	(*DeleteTrafficDataByDetectionPointRequest)(nil),                // 10: pb.DeleteTrafficDataByDetectionPointRequest
	(*BulkCreateTrafficDataByDetectionPointRequest)(nil),            // 11: pb.BulkCreateTrafficDataByDetectionPointRequest
	(*GetTrafficDataByDetectionPointStatisticsRequest)(nil),         // 12: pb.GetTrafficDataByDetectionPointStatisticsRequest
	(*ListTrafficDataByDetectionPointDailyRequest)(nil),             // 13: pb.ListTrafficDataByDetectionPointDailyRequest
	(*DownloadTrafficDataByDetectionPointRequest)(nil),              // 14: pb.DownloadTrafficDataByDetectionPointRequest
	(*emptypb.Empty)(nil), // 15: google.protobuf.Empty
	(*BulkCreateTrafficDataByDetectionPointResponse)(nil),    // 16: pb.BulkCreateTrafficDataByDetectionPointResponse
	(*GetTrafficDataByDetectionPointStatisticsResponse)(nil), // 17: pb.GetTrafficDataByDetectionPointStatisticsResponse
	(*DownloadResponse)(nil),                                 // 18: pb.DownloadResponse
}
var file_services_history_hour_traffic_data_detection_point_service_proto_depIdxs = []int32{
	7,  // 0: pb.ListHistoryHourTrafficDataByDetectionPointResponse.history_hour_traffic_data_by_detection_points:type_name -> pb.HistoryHourTrafficDataByDetectionPoint
	7,  // 1: pb.GetHistoryHourTrafficDataByDetectionPointResponse.history_hour_traffic_data_by_detection_point:type_name -> pb.HistoryHourTrafficDataByDetectionPoint
	7,  // 2: pb.CreateHistoryHourTrafficDataByDetectionPointRequest.history_hour_traffic_data_by_detection_point:type_name -> pb.HistoryHourTrafficDataByDetectionPoint
	7,  // 3: pb.CreateHistoryHourTrafficDataByDetectionPointResponse.history_hour_traffic_data_by_detection_point:type_name -> pb.HistoryHourTrafficDataByDetectionPoint
	7,  // 4: pb.UpdateHistoryHourTrafficDataByDetectionPointRequest.history_hour_traffic_data_by_detection_point:type_name -> pb.HistoryHourTrafficDataByDetectionPoint
	7,  // 5: pb.UpdateHistoryHourTrafficDataByDetectionPointResponse.history_hour_traffic_data_by_detection_point:type_name -> pb.HistoryHourTrafficDataByDetectionPoint
	7,  // 6: pb.ListHistoryHourTrafficDataByDetectionPointDailyResponse.daily_stats:type_name -> pb.HistoryHourTrafficDataByDetectionPoint
	8,  // 7: pb.HistoryHourTrafficDataByDetectionPointService.ListHistoryHourTrafficDataByDetectionPoint:input_type -> pb.ListTrafficDataByDetectionPointRequest
	9,  // 8: pb.HistoryHourTrafficDataByDetectionPointService.GetHistoryHourTrafficDataByDetectionPoint:input_type -> pb.GetTrafficDataByDetectionPointRequest
	2,  // 9: pb.HistoryHourTrafficDataByDetectionPointService.CreateHistoryHourTrafficDataByDetectionPoint:input_type -> pb.CreateHistoryHourTrafficDataByDetectionPointRequest
	4,  // 10: pb.HistoryHourTrafficDataByDetectionPointService.UpdateHistoryHourTrafficDataByDetectionPoint:input_type -> pb.UpdateHistoryHourTrafficDataByDetectionPointRequest
	10, // 11: pb.HistoryHourTrafficDataByDetectionPointService.DeleteHistoryHourTrafficDataByDetectionPoint:input_type -> pb.DeleteTrafficDataByDetectionPointRequest
	11, // 12: pb.HistoryHourTrafficDataByDetectionPointService.BulkCreateHistoryHourTrafficDataByDetectionPoint:input_type -> pb.BulkCreateTrafficDataByDetectionPointRequest
	12, // 13: pb.HistoryHourTrafficDataByDetectionPointService.GetHistoryHourTrafficDataByDetectionPointStatistics:input_type -> pb.GetTrafficDataByDetectionPointStatisticsRequest
	13, // 14: pb.HistoryHourTrafficDataByDetectionPointService.ListHistoryHourTrafficDataByDetectionPointDaily:input_type -> pb.ListTrafficDataByDetectionPointDailyRequest
	14, // 15: pb.HistoryHourTrafficDataByDetectionPointService.DownloadHistoryHourTrafficDataByDetectionPoint:input_type -> pb.DownloadTrafficDataByDetectionPointRequest
	0,  // 16: pb.HistoryHourTrafficDataByDetectionPointService.ListHistoryHourTrafficDataByDetectionPoint:output_type -> pb.ListHistoryHourTrafficDataByDetectionPointResponse
	1,  // 17: pb.HistoryHourTrafficDataByDetectionPointService.GetHistoryHourTrafficDataByDetectionPoint:output_type -> pb.GetHistoryHourTrafficDataByDetectionPointResponse
	3,  // 18: pb.HistoryHourTrafficDataByDetectionPointService.CreateHistoryHourTrafficDataByDetectionPoint:output_type -> pb.CreateHistoryHourTrafficDataByDetectionPointResponse
	5,  // 19: pb.HistoryHourTrafficDataByDetectionPointService.UpdateHistoryHourTrafficDataByDetectionPoint:output_type -> pb.UpdateHistoryHourTrafficDataByDetectionPointResponse
	15, // 20: pb.HistoryHourTrafficDataByDetectionPointService.DeleteHistoryHourTrafficDataByDetectionPoint:output_type -> google.protobuf.Empty
	16, // 21: pb.HistoryHourTrafficDataByDetectionPointService.BulkCreateHistoryHourTrafficDataByDetectionPoint:output_type -> pb.BulkCreateTrafficDataByDetectionPointResponse
	17, // 22: pb.HistoryHourTrafficDataByDetectionPointService.GetHistoryHourTrafficDataByDetectionPointStatistics:output_type -> pb.GetTrafficDataByDetectionPointStatisticsResponse
	6,  // 23: pb.HistoryHourTrafficDataByDetectionPointService.ListHistoryHourTrafficDataByDetectionPointDaily:output_type -> pb.ListHistoryHourTrafficDataByDetectionPointDailyResponse
	18, // 24: pb.HistoryHourTrafficDataByDetectionPointService.DownloadHistoryHourTrafficDataByDetectionPoint:output_type -> pb.DownloadResponse
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_services_history_hour_traffic_data_detection_point_service_proto_init() }
func file_services_history_hour_traffic_data_detection_point_service_proto_init() {
	if File_services_history_hour_traffic_data_detection_point_service_proto != nil {
		return
	}
	file_dtos_history_hour_traffic_data_detection_point_proto_init()
	file_dtos_traffic_requests_proto_init()
	file_dtos_traffic_responses_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_history_hour_traffic_data_detection_point_service_proto_rawDesc), len(file_services_history_hour_traffic_data_detection_point_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_history_hour_traffic_data_detection_point_service_proto_goTypes,
		DependencyIndexes: file_services_history_hour_traffic_data_detection_point_service_proto_depIdxs,
		MessageInfos:      file_services_history_hour_traffic_data_detection_point_service_proto_msgTypes,
	}.Build()
	File_services_history_hour_traffic_data_detection_point_service_proto = out.File
	file_services_history_hour_traffic_data_detection_point_service_proto_goTypes = nil
	file_services_history_hour_traffic_data_detection_point_service_proto_depIdxs = nil
}
