// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: services/history_hour_traffic_data_detection_point.service.proto

/*
Package pb is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package pb

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

var (
	filter_HistoryHourTrafficDataByDetectionPointService_ListHistoryHourTrafficDataByDetectionPoint_0 = &utilities.DoubleArray{Encoding: map[string]int{}, Base: []int(nil), Check: []int(nil)}
)

func request_HistoryHourTrafficDataByDetectionPointService_ListHistoryHourTrafficDataByDetectionPoint_0(ctx context.Context, marshaler runtime.Marshaler, client HistoryHourTrafficDataByDetectionPointServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq ListTrafficDataByDetectionPointRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_HistoryHourTrafficDataByDetectionPointService_ListHistoryHourTrafficDataByDetectionPoint_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.ListHistoryHourTrafficDataByDetectionPoint(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_HistoryHourTrafficDataByDetectionPointService_ListHistoryHourTrafficDataByDetectionPoint_0(ctx context.Context, marshaler runtime.Marshaler, server HistoryHourTrafficDataByDetectionPointServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq ListTrafficDataByDetectionPointRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_HistoryHourTrafficDataByDetectionPointService_ListHistoryHourTrafficDataByDetectionPoint_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.ListHistoryHourTrafficDataByDetectionPoint(ctx, &protoReq)
	return msg, metadata, err

}

var (
	filter_HistoryHourTrafficDataByDetectionPointService_GetHistoryHourTrafficDataByDetectionPoint_0 = &utilities.DoubleArray{Encoding: map[string]int{}, Base: []int(nil), Check: []int(nil)}
)

func request_HistoryHourTrafficDataByDetectionPointService_GetHistoryHourTrafficDataByDetectionPoint_0(ctx context.Context, marshaler runtime.Marshaler, client HistoryHourTrafficDataByDetectionPointServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GetTrafficDataByDetectionPointRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_HistoryHourTrafficDataByDetectionPointService_GetHistoryHourTrafficDataByDetectionPoint_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.GetHistoryHourTrafficDataByDetectionPoint(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_HistoryHourTrafficDataByDetectionPointService_GetHistoryHourTrafficDataByDetectionPoint_0(ctx context.Context, marshaler runtime.Marshaler, server HistoryHourTrafficDataByDetectionPointServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GetTrafficDataByDetectionPointRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_HistoryHourTrafficDataByDetectionPointService_GetHistoryHourTrafficDataByDetectionPoint_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.GetHistoryHourTrafficDataByDetectionPoint(ctx, &protoReq)
	return msg, metadata, err

}

func request_HistoryHourTrafficDataByDetectionPointService_CreateHistoryHourTrafficDataByDetectionPoint_0(ctx context.Context, marshaler runtime.Marshaler, client HistoryHourTrafficDataByDetectionPointServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq CreateHistoryHourTrafficDataByDetectionPointRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.CreateHistoryHourTrafficDataByDetectionPoint(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_HistoryHourTrafficDataByDetectionPointService_CreateHistoryHourTrafficDataByDetectionPoint_0(ctx context.Context, marshaler runtime.Marshaler, server HistoryHourTrafficDataByDetectionPointServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq CreateHistoryHourTrafficDataByDetectionPointRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.CreateHistoryHourTrafficDataByDetectionPoint(ctx, &protoReq)
	return msg, metadata, err

}

func request_HistoryHourTrafficDataByDetectionPointService_UpdateHistoryHourTrafficDataByDetectionPoint_0(ctx context.Context, marshaler runtime.Marshaler, client HistoryHourTrafficDataByDetectionPointServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq UpdateHistoryHourTrafficDataByDetectionPointRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.UpdateHistoryHourTrafficDataByDetectionPoint(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_HistoryHourTrafficDataByDetectionPointService_UpdateHistoryHourTrafficDataByDetectionPoint_0(ctx context.Context, marshaler runtime.Marshaler, server HistoryHourTrafficDataByDetectionPointServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq UpdateHistoryHourTrafficDataByDetectionPointRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.UpdateHistoryHourTrafficDataByDetectionPoint(ctx, &protoReq)
	return msg, metadata, err

}

var (
	filter_HistoryHourTrafficDataByDetectionPointService_DeleteHistoryHourTrafficDataByDetectionPoint_0 = &utilities.DoubleArray{Encoding: map[string]int{}, Base: []int(nil), Check: []int(nil)}
)

func request_HistoryHourTrafficDataByDetectionPointService_DeleteHistoryHourTrafficDataByDetectionPoint_0(ctx context.Context, marshaler runtime.Marshaler, client HistoryHourTrafficDataByDetectionPointServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq DeleteTrafficDataByDetectionPointRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_HistoryHourTrafficDataByDetectionPointService_DeleteHistoryHourTrafficDataByDetectionPoint_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.DeleteHistoryHourTrafficDataByDetectionPoint(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_HistoryHourTrafficDataByDetectionPointService_DeleteHistoryHourTrafficDataByDetectionPoint_0(ctx context.Context, marshaler runtime.Marshaler, server HistoryHourTrafficDataByDetectionPointServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq DeleteTrafficDataByDetectionPointRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_HistoryHourTrafficDataByDetectionPointService_DeleteHistoryHourTrafficDataByDetectionPoint_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.DeleteHistoryHourTrafficDataByDetectionPoint(ctx, &protoReq)
	return msg, metadata, err

}

func request_HistoryHourTrafficDataByDetectionPointService_BulkCreateHistoryHourTrafficDataByDetectionPoint_0(ctx context.Context, marshaler runtime.Marshaler, client HistoryHourTrafficDataByDetectionPointServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq BulkCreateTrafficDataByDetectionPointRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.BulkCreateHistoryHourTrafficDataByDetectionPoint(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_HistoryHourTrafficDataByDetectionPointService_BulkCreateHistoryHourTrafficDataByDetectionPoint_0(ctx context.Context, marshaler runtime.Marshaler, server HistoryHourTrafficDataByDetectionPointServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq BulkCreateTrafficDataByDetectionPointRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.BulkCreateHistoryHourTrafficDataByDetectionPoint(ctx, &protoReq)
	return msg, metadata, err

}

var (
	filter_HistoryHourTrafficDataByDetectionPointService_GetHistoryHourTrafficDataByDetectionPointStatistics_0 = &utilities.DoubleArray{Encoding: map[string]int{}, Base: []int(nil), Check: []int(nil)}
)

func request_HistoryHourTrafficDataByDetectionPointService_GetHistoryHourTrafficDataByDetectionPointStatistics_0(ctx context.Context, marshaler runtime.Marshaler, client HistoryHourTrafficDataByDetectionPointServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GetTrafficDataByDetectionPointStatisticsRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_HistoryHourTrafficDataByDetectionPointService_GetHistoryHourTrafficDataByDetectionPointStatistics_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.GetHistoryHourTrafficDataByDetectionPointStatistics(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_HistoryHourTrafficDataByDetectionPointService_GetHistoryHourTrafficDataByDetectionPointStatistics_0(ctx context.Context, marshaler runtime.Marshaler, server HistoryHourTrafficDataByDetectionPointServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GetTrafficDataByDetectionPointStatisticsRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_HistoryHourTrafficDataByDetectionPointService_GetHistoryHourTrafficDataByDetectionPointStatistics_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.GetHistoryHourTrafficDataByDetectionPointStatistics(ctx, &protoReq)
	return msg, metadata, err

}

var (
	filter_HistoryHourTrafficDataByDetectionPointService_ListHistoryHourTrafficDataByDetectionPointDaily_0 = &utilities.DoubleArray{Encoding: map[string]int{}, Base: []int(nil), Check: []int(nil)}
)

func request_HistoryHourTrafficDataByDetectionPointService_ListHistoryHourTrafficDataByDetectionPointDaily_0(ctx context.Context, marshaler runtime.Marshaler, client HistoryHourTrafficDataByDetectionPointServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq ListTrafficDataByDetectionPointDailyRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_HistoryHourTrafficDataByDetectionPointService_ListHistoryHourTrafficDataByDetectionPointDaily_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.ListHistoryHourTrafficDataByDetectionPointDaily(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_HistoryHourTrafficDataByDetectionPointService_ListHistoryHourTrafficDataByDetectionPointDaily_0(ctx context.Context, marshaler runtime.Marshaler, server HistoryHourTrafficDataByDetectionPointServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq ListTrafficDataByDetectionPointDailyRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_HistoryHourTrafficDataByDetectionPointService_ListHistoryHourTrafficDataByDetectionPointDaily_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.ListHistoryHourTrafficDataByDetectionPointDaily(ctx, &protoReq)
	return msg, metadata, err

}

var (
	filter_HistoryHourTrafficDataByDetectionPointService_DownloadHistoryHourTrafficDataByDetectionPoint_0 = &utilities.DoubleArray{Encoding: map[string]int{}, Base: []int(nil), Check: []int(nil)}
)

func request_HistoryHourTrafficDataByDetectionPointService_DownloadHistoryHourTrafficDataByDetectionPoint_0(ctx context.Context, marshaler runtime.Marshaler, client HistoryHourTrafficDataByDetectionPointServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq DownloadTrafficDataByDetectionPointRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_HistoryHourTrafficDataByDetectionPointService_DownloadHistoryHourTrafficDataByDetectionPoint_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.DownloadHistoryHourTrafficDataByDetectionPoint(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_HistoryHourTrafficDataByDetectionPointService_DownloadHistoryHourTrafficDataByDetectionPoint_0(ctx context.Context, marshaler runtime.Marshaler, server HistoryHourTrafficDataByDetectionPointServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq DownloadTrafficDataByDetectionPointRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_HistoryHourTrafficDataByDetectionPointService_DownloadHistoryHourTrafficDataByDetectionPoint_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.DownloadHistoryHourTrafficDataByDetectionPoint(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterHistoryHourTrafficDataByDetectionPointServiceHandlerServer registers the http handlers for service HistoryHourTrafficDataByDetectionPointService to "mux".
// UnaryRPC     :call HistoryHourTrafficDataByDetectionPointServiceServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterHistoryHourTrafficDataByDetectionPointServiceHandlerFromEndpoint instead.
func RegisterHistoryHourTrafficDataByDetectionPointServiceHandlerServer(ctx context.Context, mux *runtime.ServeMux, server HistoryHourTrafficDataByDetectionPointServiceServer) error {

	mux.Handle("GET", pattern_HistoryHourTrafficDataByDetectionPointService_ListHistoryHourTrafficDataByDetectionPoint_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/pb.HistoryHourTrafficDataByDetectionPointService/ListHistoryHourTrafficDataByDetectionPoint", runtime.WithHTTPPathPattern("/api/v1/traffic/history_hour/detection_point/list"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_HistoryHourTrafficDataByDetectionPointService_ListHistoryHourTrafficDataByDetectionPoint_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryHourTrafficDataByDetectionPointService_ListHistoryHourTrafficDataByDetectionPoint_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_HistoryHourTrafficDataByDetectionPointService_GetHistoryHourTrafficDataByDetectionPoint_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/pb.HistoryHourTrafficDataByDetectionPointService/GetHistoryHourTrafficDataByDetectionPoint", runtime.WithHTTPPathPattern("/api/v1/traffic/history_hour/detection_point/single"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_HistoryHourTrafficDataByDetectionPointService_GetHistoryHourTrafficDataByDetectionPoint_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryHourTrafficDataByDetectionPointService_GetHistoryHourTrafficDataByDetectionPoint_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_HistoryHourTrafficDataByDetectionPointService_CreateHistoryHourTrafficDataByDetectionPoint_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/pb.HistoryHourTrafficDataByDetectionPointService/CreateHistoryHourTrafficDataByDetectionPoint", runtime.WithHTTPPathPattern("/api/v1/traffic/history_hour/detection_point"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_HistoryHourTrafficDataByDetectionPointService_CreateHistoryHourTrafficDataByDetectionPoint_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryHourTrafficDataByDetectionPointService_CreateHistoryHourTrafficDataByDetectionPoint_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("PATCH", pattern_HistoryHourTrafficDataByDetectionPointService_UpdateHistoryHourTrafficDataByDetectionPoint_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/pb.HistoryHourTrafficDataByDetectionPointService/UpdateHistoryHourTrafficDataByDetectionPoint", runtime.WithHTTPPathPattern("/api/v1/traffic/history_hour/detection_point"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_HistoryHourTrafficDataByDetectionPointService_UpdateHistoryHourTrafficDataByDetectionPoint_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryHourTrafficDataByDetectionPointService_UpdateHistoryHourTrafficDataByDetectionPoint_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("DELETE", pattern_HistoryHourTrafficDataByDetectionPointService_DeleteHistoryHourTrafficDataByDetectionPoint_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/pb.HistoryHourTrafficDataByDetectionPointService/DeleteHistoryHourTrafficDataByDetectionPoint", runtime.WithHTTPPathPattern("/api/v1/traffic/history_hour/detection_point"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_HistoryHourTrafficDataByDetectionPointService_DeleteHistoryHourTrafficDataByDetectionPoint_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryHourTrafficDataByDetectionPointService_DeleteHistoryHourTrafficDataByDetectionPoint_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_HistoryHourTrafficDataByDetectionPointService_BulkCreateHistoryHourTrafficDataByDetectionPoint_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/pb.HistoryHourTrafficDataByDetectionPointService/BulkCreateHistoryHourTrafficDataByDetectionPoint", runtime.WithHTTPPathPattern("/api/v1/traffic/history_hour/detection_point/bulk"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_HistoryHourTrafficDataByDetectionPointService_BulkCreateHistoryHourTrafficDataByDetectionPoint_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryHourTrafficDataByDetectionPointService_BulkCreateHistoryHourTrafficDataByDetectionPoint_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_HistoryHourTrafficDataByDetectionPointService_GetHistoryHourTrafficDataByDetectionPointStatistics_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/pb.HistoryHourTrafficDataByDetectionPointService/GetHistoryHourTrafficDataByDetectionPointStatistics", runtime.WithHTTPPathPattern("/api/v1/traffic/history_hour/detection_point/statistics"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_HistoryHourTrafficDataByDetectionPointService_GetHistoryHourTrafficDataByDetectionPointStatistics_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryHourTrafficDataByDetectionPointService_GetHistoryHourTrafficDataByDetectionPointStatistics_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_HistoryHourTrafficDataByDetectionPointService_ListHistoryHourTrafficDataByDetectionPointDaily_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/pb.HistoryHourTrafficDataByDetectionPointService/ListHistoryHourTrafficDataByDetectionPointDaily", runtime.WithHTTPPathPattern("/api/v1/traffic/history_hour/detection_point/daily"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_HistoryHourTrafficDataByDetectionPointService_ListHistoryHourTrafficDataByDetectionPointDaily_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryHourTrafficDataByDetectionPointService_ListHistoryHourTrafficDataByDetectionPointDaily_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_HistoryHourTrafficDataByDetectionPointService_DownloadHistoryHourTrafficDataByDetectionPoint_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/pb.HistoryHourTrafficDataByDetectionPointService/DownloadHistoryHourTrafficDataByDetectionPoint", runtime.WithHTTPPathPattern("/api/v1/traffic/history_hour/detection_point/download"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_HistoryHourTrafficDataByDetectionPointService_DownloadHistoryHourTrafficDataByDetectionPoint_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryHourTrafficDataByDetectionPointService_DownloadHistoryHourTrafficDataByDetectionPoint_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterHistoryHourTrafficDataByDetectionPointServiceHandlerFromEndpoint is same as RegisterHistoryHourTrafficDataByDetectionPointServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterHistoryHourTrafficDataByDetectionPointServiceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.DialContext(ctx, endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterHistoryHourTrafficDataByDetectionPointServiceHandler(ctx, mux, conn)
}

// RegisterHistoryHourTrafficDataByDetectionPointServiceHandler registers the http handlers for service HistoryHourTrafficDataByDetectionPointService to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterHistoryHourTrafficDataByDetectionPointServiceHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterHistoryHourTrafficDataByDetectionPointServiceHandlerClient(ctx, mux, NewHistoryHourTrafficDataByDetectionPointServiceClient(conn))
}

// RegisterHistoryHourTrafficDataByDetectionPointServiceHandlerClient registers the http handlers for service HistoryHourTrafficDataByDetectionPointService
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "HistoryHourTrafficDataByDetectionPointServiceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "HistoryHourTrafficDataByDetectionPointServiceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "HistoryHourTrafficDataByDetectionPointServiceClient" to call the correct interceptors.
func RegisterHistoryHourTrafficDataByDetectionPointServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client HistoryHourTrafficDataByDetectionPointServiceClient) error {

	mux.Handle("GET", pattern_HistoryHourTrafficDataByDetectionPointService_ListHistoryHourTrafficDataByDetectionPoint_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/pb.HistoryHourTrafficDataByDetectionPointService/ListHistoryHourTrafficDataByDetectionPoint", runtime.WithHTTPPathPattern("/api/v1/traffic/history_hour/detection_point/list"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_HistoryHourTrafficDataByDetectionPointService_ListHistoryHourTrafficDataByDetectionPoint_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryHourTrafficDataByDetectionPointService_ListHistoryHourTrafficDataByDetectionPoint_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_HistoryHourTrafficDataByDetectionPointService_GetHistoryHourTrafficDataByDetectionPoint_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/pb.HistoryHourTrafficDataByDetectionPointService/GetHistoryHourTrafficDataByDetectionPoint", runtime.WithHTTPPathPattern("/api/v1/traffic/history_hour/detection_point/single"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_HistoryHourTrafficDataByDetectionPointService_GetHistoryHourTrafficDataByDetectionPoint_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryHourTrafficDataByDetectionPointService_GetHistoryHourTrafficDataByDetectionPoint_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_HistoryHourTrafficDataByDetectionPointService_CreateHistoryHourTrafficDataByDetectionPoint_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/pb.HistoryHourTrafficDataByDetectionPointService/CreateHistoryHourTrafficDataByDetectionPoint", runtime.WithHTTPPathPattern("/api/v1/traffic/history_hour/detection_point"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_HistoryHourTrafficDataByDetectionPointService_CreateHistoryHourTrafficDataByDetectionPoint_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryHourTrafficDataByDetectionPointService_CreateHistoryHourTrafficDataByDetectionPoint_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("PATCH", pattern_HistoryHourTrafficDataByDetectionPointService_UpdateHistoryHourTrafficDataByDetectionPoint_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/pb.HistoryHourTrafficDataByDetectionPointService/UpdateHistoryHourTrafficDataByDetectionPoint", runtime.WithHTTPPathPattern("/api/v1/traffic/history_hour/detection_point"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_HistoryHourTrafficDataByDetectionPointService_UpdateHistoryHourTrafficDataByDetectionPoint_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryHourTrafficDataByDetectionPointService_UpdateHistoryHourTrafficDataByDetectionPoint_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("DELETE", pattern_HistoryHourTrafficDataByDetectionPointService_DeleteHistoryHourTrafficDataByDetectionPoint_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/pb.HistoryHourTrafficDataByDetectionPointService/DeleteHistoryHourTrafficDataByDetectionPoint", runtime.WithHTTPPathPattern("/api/v1/traffic/history_hour/detection_point"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_HistoryHourTrafficDataByDetectionPointService_DeleteHistoryHourTrafficDataByDetectionPoint_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryHourTrafficDataByDetectionPointService_DeleteHistoryHourTrafficDataByDetectionPoint_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_HistoryHourTrafficDataByDetectionPointService_BulkCreateHistoryHourTrafficDataByDetectionPoint_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/pb.HistoryHourTrafficDataByDetectionPointService/BulkCreateHistoryHourTrafficDataByDetectionPoint", runtime.WithHTTPPathPattern("/api/v1/traffic/history_hour/detection_point/bulk"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_HistoryHourTrafficDataByDetectionPointService_BulkCreateHistoryHourTrafficDataByDetectionPoint_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryHourTrafficDataByDetectionPointService_BulkCreateHistoryHourTrafficDataByDetectionPoint_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_HistoryHourTrafficDataByDetectionPointService_GetHistoryHourTrafficDataByDetectionPointStatistics_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/pb.HistoryHourTrafficDataByDetectionPointService/GetHistoryHourTrafficDataByDetectionPointStatistics", runtime.WithHTTPPathPattern("/api/v1/traffic/history_hour/detection_point/statistics"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_HistoryHourTrafficDataByDetectionPointService_GetHistoryHourTrafficDataByDetectionPointStatistics_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryHourTrafficDataByDetectionPointService_GetHistoryHourTrafficDataByDetectionPointStatistics_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_HistoryHourTrafficDataByDetectionPointService_ListHistoryHourTrafficDataByDetectionPointDaily_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/pb.HistoryHourTrafficDataByDetectionPointService/ListHistoryHourTrafficDataByDetectionPointDaily", runtime.WithHTTPPathPattern("/api/v1/traffic/history_hour/detection_point/daily"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_HistoryHourTrafficDataByDetectionPointService_ListHistoryHourTrafficDataByDetectionPointDaily_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryHourTrafficDataByDetectionPointService_ListHistoryHourTrafficDataByDetectionPointDaily_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_HistoryHourTrafficDataByDetectionPointService_DownloadHistoryHourTrafficDataByDetectionPoint_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/pb.HistoryHourTrafficDataByDetectionPointService/DownloadHistoryHourTrafficDataByDetectionPoint", runtime.WithHTTPPathPattern("/api/v1/traffic/history_hour/detection_point/download"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_HistoryHourTrafficDataByDetectionPointService_DownloadHistoryHourTrafficDataByDetectionPoint_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryHourTrafficDataByDetectionPointService_DownloadHistoryHourTrafficDataByDetectionPoint_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_HistoryHourTrafficDataByDetectionPointService_ListHistoryHourTrafficDataByDetectionPoint_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 2, 4, 2, 5}, []string{"api", "v1", "traffic", "history_hour", "detection_point", "list"}, ""))

	pattern_HistoryHourTrafficDataByDetectionPointService_GetHistoryHourTrafficDataByDetectionPoint_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 2, 4, 2, 5}, []string{"api", "v1", "traffic", "history_hour", "detection_point", "single"}, ""))

	pattern_HistoryHourTrafficDataByDetectionPointService_CreateHistoryHourTrafficDataByDetectionPoint_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 2, 4}, []string{"api", "v1", "traffic", "history_hour", "detection_point"}, ""))

	pattern_HistoryHourTrafficDataByDetectionPointService_UpdateHistoryHourTrafficDataByDetectionPoint_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 2, 4}, []string{"api", "v1", "traffic", "history_hour", "detection_point"}, ""))

	pattern_HistoryHourTrafficDataByDetectionPointService_DeleteHistoryHourTrafficDataByDetectionPoint_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 2, 4}, []string{"api", "v1", "traffic", "history_hour", "detection_point"}, ""))

	pattern_HistoryHourTrafficDataByDetectionPointService_BulkCreateHistoryHourTrafficDataByDetectionPoint_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 2, 4, 2, 5}, []string{"api", "v1", "traffic", "history_hour", "detection_point", "bulk"}, ""))

	pattern_HistoryHourTrafficDataByDetectionPointService_GetHistoryHourTrafficDataByDetectionPointStatistics_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 2, 4, 2, 5}, []string{"api", "v1", "traffic", "history_hour", "detection_point", "statistics"}, ""))

	pattern_HistoryHourTrafficDataByDetectionPointService_ListHistoryHourTrafficDataByDetectionPointDaily_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 2, 4, 2, 5}, []string{"api", "v1", "traffic", "history_hour", "detection_point", "daily"}, ""))

	pattern_HistoryHourTrafficDataByDetectionPointService_DownloadHistoryHourTrafficDataByDetectionPoint_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 2, 4, 2, 5}, []string{"api", "v1", "traffic", "history_hour", "detection_point", "download"}, ""))
)

var (
	forward_HistoryHourTrafficDataByDetectionPointService_ListHistoryHourTrafficDataByDetectionPoint_0 = runtime.ForwardResponseMessage

	forward_HistoryHourTrafficDataByDetectionPointService_GetHistoryHourTrafficDataByDetectionPoint_0 = runtime.ForwardResponseMessage

	forward_HistoryHourTrafficDataByDetectionPointService_CreateHistoryHourTrafficDataByDetectionPoint_0 = runtime.ForwardResponseMessage

	forward_HistoryHourTrafficDataByDetectionPointService_UpdateHistoryHourTrafficDataByDetectionPoint_0 = runtime.ForwardResponseMessage

	forward_HistoryHourTrafficDataByDetectionPointService_DeleteHistoryHourTrafficDataByDetectionPoint_0 = runtime.ForwardResponseMessage

	forward_HistoryHourTrafficDataByDetectionPointService_BulkCreateHistoryHourTrafficDataByDetectionPoint_0 = runtime.ForwardResponseMessage

	forward_HistoryHourTrafficDataByDetectionPointService_GetHistoryHourTrafficDataByDetectionPointStatistics_0 = runtime.ForwardResponseMessage

	forward_HistoryHourTrafficDataByDetectionPointService_ListHistoryHourTrafficDataByDetectionPointDaily_0 = runtime.ForwardResponseMessage

	forward_HistoryHourTrafficDataByDetectionPointService_DownloadHistoryHourTrafficDataByDetectionPoint_0 = runtime.ForwardResponseMessage
)
