// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: services/history_hour_traffic_data_detection_point_lane.service.proto

/*
Package pb is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package pb

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

var (
	filter_HistoryHourTrafficDataByDetectionPointByLaneService_ListHistoryHourTrafficDataByDetectionPointByLane_0 = &utilities.DoubleArray{Encoding: map[string]int{}, Base: []int(nil), Check: []int(nil)}
)

func request_HistoryHourTrafficDataByDetectionPointByLaneService_ListHistoryHourTrafficDataByDetectionPointByLane_0(ctx context.Context, marshaler runtime.Marshaler, client HistoryHourTrafficDataByDetectionPointByLaneServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq ListTrafficDataByDetectionPointByLaneRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_HistoryHourTrafficDataByDetectionPointByLaneService_ListHistoryHourTrafficDataByDetectionPointByLane_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.ListHistoryHourTrafficDataByDetectionPointByLane(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_HistoryHourTrafficDataByDetectionPointByLaneService_ListHistoryHourTrafficDataByDetectionPointByLane_0(ctx context.Context, marshaler runtime.Marshaler, server HistoryHourTrafficDataByDetectionPointByLaneServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq ListTrafficDataByDetectionPointByLaneRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_HistoryHourTrafficDataByDetectionPointByLaneService_ListHistoryHourTrafficDataByDetectionPointByLane_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.ListHistoryHourTrafficDataByDetectionPointByLane(ctx, &protoReq)
	return msg, metadata, err

}

var (
	filter_HistoryHourTrafficDataByDetectionPointByLaneService_GetHistoryHourTrafficDataByDetectionPointByLane_0 = &utilities.DoubleArray{Encoding: map[string]int{}, Base: []int(nil), Check: []int(nil)}
)

func request_HistoryHourTrafficDataByDetectionPointByLaneService_GetHistoryHourTrafficDataByDetectionPointByLane_0(ctx context.Context, marshaler runtime.Marshaler, client HistoryHourTrafficDataByDetectionPointByLaneServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GetTrafficDataByDetectionPointByLaneRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_HistoryHourTrafficDataByDetectionPointByLaneService_GetHistoryHourTrafficDataByDetectionPointByLane_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.GetHistoryHourTrafficDataByDetectionPointByLane(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_HistoryHourTrafficDataByDetectionPointByLaneService_GetHistoryHourTrafficDataByDetectionPointByLane_0(ctx context.Context, marshaler runtime.Marshaler, server HistoryHourTrafficDataByDetectionPointByLaneServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GetTrafficDataByDetectionPointByLaneRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_HistoryHourTrafficDataByDetectionPointByLaneService_GetHistoryHourTrafficDataByDetectionPointByLane_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.GetHistoryHourTrafficDataByDetectionPointByLane(ctx, &protoReq)
	return msg, metadata, err

}

func request_HistoryHourTrafficDataByDetectionPointByLaneService_CreateHistoryHourTrafficDataByDetectionPointByLane_0(ctx context.Context, marshaler runtime.Marshaler, client HistoryHourTrafficDataByDetectionPointByLaneServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq CreateHistoryHourTrafficDataByDetectionPointByLaneRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.CreateHistoryHourTrafficDataByDetectionPointByLane(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_HistoryHourTrafficDataByDetectionPointByLaneService_CreateHistoryHourTrafficDataByDetectionPointByLane_0(ctx context.Context, marshaler runtime.Marshaler, server HistoryHourTrafficDataByDetectionPointByLaneServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq CreateHistoryHourTrafficDataByDetectionPointByLaneRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.CreateHistoryHourTrafficDataByDetectionPointByLane(ctx, &protoReq)
	return msg, metadata, err

}

func request_HistoryHourTrafficDataByDetectionPointByLaneService_UpdateHistoryHourTrafficDataByDetectionPointByLane_0(ctx context.Context, marshaler runtime.Marshaler, client HistoryHourTrafficDataByDetectionPointByLaneServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq UpdateHistoryHourTrafficDataByDetectionPointByLaneRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.UpdateHistoryHourTrafficDataByDetectionPointByLane(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_HistoryHourTrafficDataByDetectionPointByLaneService_UpdateHistoryHourTrafficDataByDetectionPointByLane_0(ctx context.Context, marshaler runtime.Marshaler, server HistoryHourTrafficDataByDetectionPointByLaneServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq UpdateHistoryHourTrafficDataByDetectionPointByLaneRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.UpdateHistoryHourTrafficDataByDetectionPointByLane(ctx, &protoReq)
	return msg, metadata, err

}

var (
	filter_HistoryHourTrafficDataByDetectionPointByLaneService_DeleteHistoryHourTrafficDataByDetectionPointByLane_0 = &utilities.DoubleArray{Encoding: map[string]int{}, Base: []int(nil), Check: []int(nil)}
)

func request_HistoryHourTrafficDataByDetectionPointByLaneService_DeleteHistoryHourTrafficDataByDetectionPointByLane_0(ctx context.Context, marshaler runtime.Marshaler, client HistoryHourTrafficDataByDetectionPointByLaneServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq DeleteTrafficDataByDetectionPointByLaneRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_HistoryHourTrafficDataByDetectionPointByLaneService_DeleteHistoryHourTrafficDataByDetectionPointByLane_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.DeleteHistoryHourTrafficDataByDetectionPointByLane(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_HistoryHourTrafficDataByDetectionPointByLaneService_DeleteHistoryHourTrafficDataByDetectionPointByLane_0(ctx context.Context, marshaler runtime.Marshaler, server HistoryHourTrafficDataByDetectionPointByLaneServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq DeleteTrafficDataByDetectionPointByLaneRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_HistoryHourTrafficDataByDetectionPointByLaneService_DeleteHistoryHourTrafficDataByDetectionPointByLane_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.DeleteHistoryHourTrafficDataByDetectionPointByLane(ctx, &protoReq)
	return msg, metadata, err

}

func request_HistoryHourTrafficDataByDetectionPointByLaneService_BulkCreateHistoryHourTrafficDataByDetectionPointByLane_0(ctx context.Context, marshaler runtime.Marshaler, client HistoryHourTrafficDataByDetectionPointByLaneServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq BulkCreateTrafficDataByDetectionPointByLaneRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.BulkCreateHistoryHourTrafficDataByDetectionPointByLane(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_HistoryHourTrafficDataByDetectionPointByLaneService_BulkCreateHistoryHourTrafficDataByDetectionPointByLane_0(ctx context.Context, marshaler runtime.Marshaler, server HistoryHourTrafficDataByDetectionPointByLaneServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq BulkCreateTrafficDataByDetectionPointByLaneRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.BulkCreateHistoryHourTrafficDataByDetectionPointByLane(ctx, &protoReq)
	return msg, metadata, err

}

var (
	filter_HistoryHourTrafficDataByDetectionPointByLaneService_GetHistoryHourTrafficDataByDetectionPointByLaneStatistics_0 = &utilities.DoubleArray{Encoding: map[string]int{}, Base: []int(nil), Check: []int(nil)}
)

func request_HistoryHourTrafficDataByDetectionPointByLaneService_GetHistoryHourTrafficDataByDetectionPointByLaneStatistics_0(ctx context.Context, marshaler runtime.Marshaler, client HistoryHourTrafficDataByDetectionPointByLaneServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GetTrafficDataByDetectionPointByLaneStatisticsRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_HistoryHourTrafficDataByDetectionPointByLaneService_GetHistoryHourTrafficDataByDetectionPointByLaneStatistics_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.GetHistoryHourTrafficDataByDetectionPointByLaneStatistics(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_HistoryHourTrafficDataByDetectionPointByLaneService_GetHistoryHourTrafficDataByDetectionPointByLaneStatistics_0(ctx context.Context, marshaler runtime.Marshaler, server HistoryHourTrafficDataByDetectionPointByLaneServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GetTrafficDataByDetectionPointByLaneStatisticsRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_HistoryHourTrafficDataByDetectionPointByLaneService_GetHistoryHourTrafficDataByDetectionPointByLaneStatistics_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.GetHistoryHourTrafficDataByDetectionPointByLaneStatistics(ctx, &protoReq)
	return msg, metadata, err

}

var (
	filter_HistoryHourTrafficDataByDetectionPointByLaneService_ListHistoryHourTrafficDataByDetectionPointByLaneDaily_0 = &utilities.DoubleArray{Encoding: map[string]int{}, Base: []int(nil), Check: []int(nil)}
)

func request_HistoryHourTrafficDataByDetectionPointByLaneService_ListHistoryHourTrafficDataByDetectionPointByLaneDaily_0(ctx context.Context, marshaler runtime.Marshaler, client HistoryHourTrafficDataByDetectionPointByLaneServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq ListTrafficDataByDetectionPointByLaneDailyRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_HistoryHourTrafficDataByDetectionPointByLaneService_ListHistoryHourTrafficDataByDetectionPointByLaneDaily_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.ListHistoryHourTrafficDataByDetectionPointByLaneDaily(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_HistoryHourTrafficDataByDetectionPointByLaneService_ListHistoryHourTrafficDataByDetectionPointByLaneDaily_0(ctx context.Context, marshaler runtime.Marshaler, server HistoryHourTrafficDataByDetectionPointByLaneServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq ListTrafficDataByDetectionPointByLaneDailyRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_HistoryHourTrafficDataByDetectionPointByLaneService_ListHistoryHourTrafficDataByDetectionPointByLaneDaily_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.ListHistoryHourTrafficDataByDetectionPointByLaneDaily(ctx, &protoReq)
	return msg, metadata, err

}

var (
	filter_HistoryHourTrafficDataByDetectionPointByLaneService_DownloadHistoryHourTrafficDataByDetectionPointByLane_0 = &utilities.DoubleArray{Encoding: map[string]int{}, Base: []int(nil), Check: []int(nil)}
)

func request_HistoryHourTrafficDataByDetectionPointByLaneService_DownloadHistoryHourTrafficDataByDetectionPointByLane_0(ctx context.Context, marshaler runtime.Marshaler, client HistoryHourTrafficDataByDetectionPointByLaneServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq DownloadTrafficDataByDetectionPointByLaneRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_HistoryHourTrafficDataByDetectionPointByLaneService_DownloadHistoryHourTrafficDataByDetectionPointByLane_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.DownloadHistoryHourTrafficDataByDetectionPointByLane(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_HistoryHourTrafficDataByDetectionPointByLaneService_DownloadHistoryHourTrafficDataByDetectionPointByLane_0(ctx context.Context, marshaler runtime.Marshaler, server HistoryHourTrafficDataByDetectionPointByLaneServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq DownloadTrafficDataByDetectionPointByLaneRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_HistoryHourTrafficDataByDetectionPointByLaneService_DownloadHistoryHourTrafficDataByDetectionPointByLane_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.DownloadHistoryHourTrafficDataByDetectionPointByLane(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterHistoryHourTrafficDataByDetectionPointByLaneServiceHandlerServer registers the http handlers for service HistoryHourTrafficDataByDetectionPointByLaneService to "mux".
// UnaryRPC     :call HistoryHourTrafficDataByDetectionPointByLaneServiceServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterHistoryHourTrafficDataByDetectionPointByLaneServiceHandlerFromEndpoint instead.
func RegisterHistoryHourTrafficDataByDetectionPointByLaneServiceHandlerServer(ctx context.Context, mux *runtime.ServeMux, server HistoryHourTrafficDataByDetectionPointByLaneServiceServer) error {

	mux.Handle("GET", pattern_HistoryHourTrafficDataByDetectionPointByLaneService_ListHistoryHourTrafficDataByDetectionPointByLane_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/pb.HistoryHourTrafficDataByDetectionPointByLaneService/ListHistoryHourTrafficDataByDetectionPointByLane", runtime.WithHTTPPathPattern("/api/v1/traffic/history_hour/detection_point/lane/list"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_HistoryHourTrafficDataByDetectionPointByLaneService_ListHistoryHourTrafficDataByDetectionPointByLane_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryHourTrafficDataByDetectionPointByLaneService_ListHistoryHourTrafficDataByDetectionPointByLane_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_HistoryHourTrafficDataByDetectionPointByLaneService_GetHistoryHourTrafficDataByDetectionPointByLane_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/pb.HistoryHourTrafficDataByDetectionPointByLaneService/GetHistoryHourTrafficDataByDetectionPointByLane", runtime.WithHTTPPathPattern("/api/v1/traffic/history_hour/detection_point/lane/single"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_HistoryHourTrafficDataByDetectionPointByLaneService_GetHistoryHourTrafficDataByDetectionPointByLane_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryHourTrafficDataByDetectionPointByLaneService_GetHistoryHourTrafficDataByDetectionPointByLane_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_HistoryHourTrafficDataByDetectionPointByLaneService_CreateHistoryHourTrafficDataByDetectionPointByLane_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/pb.HistoryHourTrafficDataByDetectionPointByLaneService/CreateHistoryHourTrafficDataByDetectionPointByLane", runtime.WithHTTPPathPattern("/api/v1/traffic/history_hour/detection_point/lane"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_HistoryHourTrafficDataByDetectionPointByLaneService_CreateHistoryHourTrafficDataByDetectionPointByLane_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryHourTrafficDataByDetectionPointByLaneService_CreateHistoryHourTrafficDataByDetectionPointByLane_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("PATCH", pattern_HistoryHourTrafficDataByDetectionPointByLaneService_UpdateHistoryHourTrafficDataByDetectionPointByLane_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/pb.HistoryHourTrafficDataByDetectionPointByLaneService/UpdateHistoryHourTrafficDataByDetectionPointByLane", runtime.WithHTTPPathPattern("/api/v1/traffic/history_hour/detection_point/lane"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_HistoryHourTrafficDataByDetectionPointByLaneService_UpdateHistoryHourTrafficDataByDetectionPointByLane_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryHourTrafficDataByDetectionPointByLaneService_UpdateHistoryHourTrafficDataByDetectionPointByLane_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("DELETE", pattern_HistoryHourTrafficDataByDetectionPointByLaneService_DeleteHistoryHourTrafficDataByDetectionPointByLane_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/pb.HistoryHourTrafficDataByDetectionPointByLaneService/DeleteHistoryHourTrafficDataByDetectionPointByLane", runtime.WithHTTPPathPattern("/api/v1/traffic/history_hour/detection_point/lane"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_HistoryHourTrafficDataByDetectionPointByLaneService_DeleteHistoryHourTrafficDataByDetectionPointByLane_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryHourTrafficDataByDetectionPointByLaneService_DeleteHistoryHourTrafficDataByDetectionPointByLane_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_HistoryHourTrafficDataByDetectionPointByLaneService_BulkCreateHistoryHourTrafficDataByDetectionPointByLane_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/pb.HistoryHourTrafficDataByDetectionPointByLaneService/BulkCreateHistoryHourTrafficDataByDetectionPointByLane", runtime.WithHTTPPathPattern("/api/v1/traffic/history_hour/detection_point/lane/bulk"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_HistoryHourTrafficDataByDetectionPointByLaneService_BulkCreateHistoryHourTrafficDataByDetectionPointByLane_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryHourTrafficDataByDetectionPointByLaneService_BulkCreateHistoryHourTrafficDataByDetectionPointByLane_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_HistoryHourTrafficDataByDetectionPointByLaneService_GetHistoryHourTrafficDataByDetectionPointByLaneStatistics_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/pb.HistoryHourTrafficDataByDetectionPointByLaneService/GetHistoryHourTrafficDataByDetectionPointByLaneStatistics", runtime.WithHTTPPathPattern("/api/v1/traffic/history_hour/detection_point/lane/statistics"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_HistoryHourTrafficDataByDetectionPointByLaneService_GetHistoryHourTrafficDataByDetectionPointByLaneStatistics_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryHourTrafficDataByDetectionPointByLaneService_GetHistoryHourTrafficDataByDetectionPointByLaneStatistics_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_HistoryHourTrafficDataByDetectionPointByLaneService_ListHistoryHourTrafficDataByDetectionPointByLaneDaily_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/pb.HistoryHourTrafficDataByDetectionPointByLaneService/ListHistoryHourTrafficDataByDetectionPointByLaneDaily", runtime.WithHTTPPathPattern("/api/v1/traffic/history_hour/detection_point/lane/daily"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_HistoryHourTrafficDataByDetectionPointByLaneService_ListHistoryHourTrafficDataByDetectionPointByLaneDaily_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryHourTrafficDataByDetectionPointByLaneService_ListHistoryHourTrafficDataByDetectionPointByLaneDaily_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_HistoryHourTrafficDataByDetectionPointByLaneService_DownloadHistoryHourTrafficDataByDetectionPointByLane_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/pb.HistoryHourTrafficDataByDetectionPointByLaneService/DownloadHistoryHourTrafficDataByDetectionPointByLane", runtime.WithHTTPPathPattern("/api/v1/traffic/history_hour/detection_point/lane/download"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_HistoryHourTrafficDataByDetectionPointByLaneService_DownloadHistoryHourTrafficDataByDetectionPointByLane_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryHourTrafficDataByDetectionPointByLaneService_DownloadHistoryHourTrafficDataByDetectionPointByLane_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterHistoryHourTrafficDataByDetectionPointByLaneServiceHandlerFromEndpoint is same as RegisterHistoryHourTrafficDataByDetectionPointByLaneServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterHistoryHourTrafficDataByDetectionPointByLaneServiceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.DialContext(ctx, endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterHistoryHourTrafficDataByDetectionPointByLaneServiceHandler(ctx, mux, conn)
}

// RegisterHistoryHourTrafficDataByDetectionPointByLaneServiceHandler registers the http handlers for service HistoryHourTrafficDataByDetectionPointByLaneService to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterHistoryHourTrafficDataByDetectionPointByLaneServiceHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterHistoryHourTrafficDataByDetectionPointByLaneServiceHandlerClient(ctx, mux, NewHistoryHourTrafficDataByDetectionPointByLaneServiceClient(conn))
}

// RegisterHistoryHourTrafficDataByDetectionPointByLaneServiceHandlerClient registers the http handlers for service HistoryHourTrafficDataByDetectionPointByLaneService
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "HistoryHourTrafficDataByDetectionPointByLaneServiceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "HistoryHourTrafficDataByDetectionPointByLaneServiceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "HistoryHourTrafficDataByDetectionPointByLaneServiceClient" to call the correct interceptors.
func RegisterHistoryHourTrafficDataByDetectionPointByLaneServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client HistoryHourTrafficDataByDetectionPointByLaneServiceClient) error {

	mux.Handle("GET", pattern_HistoryHourTrafficDataByDetectionPointByLaneService_ListHistoryHourTrafficDataByDetectionPointByLane_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/pb.HistoryHourTrafficDataByDetectionPointByLaneService/ListHistoryHourTrafficDataByDetectionPointByLane", runtime.WithHTTPPathPattern("/api/v1/traffic/history_hour/detection_point/lane/list"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_HistoryHourTrafficDataByDetectionPointByLaneService_ListHistoryHourTrafficDataByDetectionPointByLane_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryHourTrafficDataByDetectionPointByLaneService_ListHistoryHourTrafficDataByDetectionPointByLane_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_HistoryHourTrafficDataByDetectionPointByLaneService_GetHistoryHourTrafficDataByDetectionPointByLane_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/pb.HistoryHourTrafficDataByDetectionPointByLaneService/GetHistoryHourTrafficDataByDetectionPointByLane", runtime.WithHTTPPathPattern("/api/v1/traffic/history_hour/detection_point/lane/single"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_HistoryHourTrafficDataByDetectionPointByLaneService_GetHistoryHourTrafficDataByDetectionPointByLane_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryHourTrafficDataByDetectionPointByLaneService_GetHistoryHourTrafficDataByDetectionPointByLane_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_HistoryHourTrafficDataByDetectionPointByLaneService_CreateHistoryHourTrafficDataByDetectionPointByLane_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/pb.HistoryHourTrafficDataByDetectionPointByLaneService/CreateHistoryHourTrafficDataByDetectionPointByLane", runtime.WithHTTPPathPattern("/api/v1/traffic/history_hour/detection_point/lane"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_HistoryHourTrafficDataByDetectionPointByLaneService_CreateHistoryHourTrafficDataByDetectionPointByLane_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryHourTrafficDataByDetectionPointByLaneService_CreateHistoryHourTrafficDataByDetectionPointByLane_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("PATCH", pattern_HistoryHourTrafficDataByDetectionPointByLaneService_UpdateHistoryHourTrafficDataByDetectionPointByLane_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/pb.HistoryHourTrafficDataByDetectionPointByLaneService/UpdateHistoryHourTrafficDataByDetectionPointByLane", runtime.WithHTTPPathPattern("/api/v1/traffic/history_hour/detection_point/lane"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_HistoryHourTrafficDataByDetectionPointByLaneService_UpdateHistoryHourTrafficDataByDetectionPointByLane_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryHourTrafficDataByDetectionPointByLaneService_UpdateHistoryHourTrafficDataByDetectionPointByLane_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("DELETE", pattern_HistoryHourTrafficDataByDetectionPointByLaneService_DeleteHistoryHourTrafficDataByDetectionPointByLane_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/pb.HistoryHourTrafficDataByDetectionPointByLaneService/DeleteHistoryHourTrafficDataByDetectionPointByLane", runtime.WithHTTPPathPattern("/api/v1/traffic/history_hour/detection_point/lane"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_HistoryHourTrafficDataByDetectionPointByLaneService_DeleteHistoryHourTrafficDataByDetectionPointByLane_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryHourTrafficDataByDetectionPointByLaneService_DeleteHistoryHourTrafficDataByDetectionPointByLane_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_HistoryHourTrafficDataByDetectionPointByLaneService_BulkCreateHistoryHourTrafficDataByDetectionPointByLane_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/pb.HistoryHourTrafficDataByDetectionPointByLaneService/BulkCreateHistoryHourTrafficDataByDetectionPointByLane", runtime.WithHTTPPathPattern("/api/v1/traffic/history_hour/detection_point/lane/bulk"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_HistoryHourTrafficDataByDetectionPointByLaneService_BulkCreateHistoryHourTrafficDataByDetectionPointByLane_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryHourTrafficDataByDetectionPointByLaneService_BulkCreateHistoryHourTrafficDataByDetectionPointByLane_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_HistoryHourTrafficDataByDetectionPointByLaneService_GetHistoryHourTrafficDataByDetectionPointByLaneStatistics_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/pb.HistoryHourTrafficDataByDetectionPointByLaneService/GetHistoryHourTrafficDataByDetectionPointByLaneStatistics", runtime.WithHTTPPathPattern("/api/v1/traffic/history_hour/detection_point/lane/statistics"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_HistoryHourTrafficDataByDetectionPointByLaneService_GetHistoryHourTrafficDataByDetectionPointByLaneStatistics_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryHourTrafficDataByDetectionPointByLaneService_GetHistoryHourTrafficDataByDetectionPointByLaneStatistics_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_HistoryHourTrafficDataByDetectionPointByLaneService_ListHistoryHourTrafficDataByDetectionPointByLaneDaily_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/pb.HistoryHourTrafficDataByDetectionPointByLaneService/ListHistoryHourTrafficDataByDetectionPointByLaneDaily", runtime.WithHTTPPathPattern("/api/v1/traffic/history_hour/detection_point/lane/daily"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_HistoryHourTrafficDataByDetectionPointByLaneService_ListHistoryHourTrafficDataByDetectionPointByLaneDaily_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryHourTrafficDataByDetectionPointByLaneService_ListHistoryHourTrafficDataByDetectionPointByLaneDaily_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_HistoryHourTrafficDataByDetectionPointByLaneService_DownloadHistoryHourTrafficDataByDetectionPointByLane_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/pb.HistoryHourTrafficDataByDetectionPointByLaneService/DownloadHistoryHourTrafficDataByDetectionPointByLane", runtime.WithHTTPPathPattern("/api/v1/traffic/history_hour/detection_point/lane/download"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_HistoryHourTrafficDataByDetectionPointByLaneService_DownloadHistoryHourTrafficDataByDetectionPointByLane_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_HistoryHourTrafficDataByDetectionPointByLaneService_DownloadHistoryHourTrafficDataByDetectionPointByLane_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_HistoryHourTrafficDataByDetectionPointByLaneService_ListHistoryHourTrafficDataByDetectionPointByLane_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 2, 4, 2, 5, 2, 6}, []string{"api", "v1", "traffic", "history_hour", "detection_point", "lane", "list"}, ""))

	pattern_HistoryHourTrafficDataByDetectionPointByLaneService_GetHistoryHourTrafficDataByDetectionPointByLane_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 2, 4, 2, 5, 2, 6}, []string{"api", "v1", "traffic", "history_hour", "detection_point", "lane", "single"}, ""))

	pattern_HistoryHourTrafficDataByDetectionPointByLaneService_CreateHistoryHourTrafficDataByDetectionPointByLane_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 2, 4, 2, 5}, []string{"api", "v1", "traffic", "history_hour", "detection_point", "lane"}, ""))

	pattern_HistoryHourTrafficDataByDetectionPointByLaneService_UpdateHistoryHourTrafficDataByDetectionPointByLane_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 2, 4, 2, 5}, []string{"api", "v1", "traffic", "history_hour", "detection_point", "lane"}, ""))

	pattern_HistoryHourTrafficDataByDetectionPointByLaneService_DeleteHistoryHourTrafficDataByDetectionPointByLane_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 2, 4, 2, 5}, []string{"api", "v1", "traffic", "history_hour", "detection_point", "lane"}, ""))

	pattern_HistoryHourTrafficDataByDetectionPointByLaneService_BulkCreateHistoryHourTrafficDataByDetectionPointByLane_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 2, 4, 2, 5, 2, 6}, []string{"api", "v1", "traffic", "history_hour", "detection_point", "lane", "bulk"}, ""))

	pattern_HistoryHourTrafficDataByDetectionPointByLaneService_GetHistoryHourTrafficDataByDetectionPointByLaneStatistics_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 2, 4, 2, 5, 2, 6}, []string{"api", "v1", "traffic", "history_hour", "detection_point", "lane", "statistics"}, ""))

	pattern_HistoryHourTrafficDataByDetectionPointByLaneService_ListHistoryHourTrafficDataByDetectionPointByLaneDaily_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 2, 4, 2, 5, 2, 6}, []string{"api", "v1", "traffic", "history_hour", "detection_point", "lane", "daily"}, ""))

	pattern_HistoryHourTrafficDataByDetectionPointByLaneService_DownloadHistoryHourTrafficDataByDetectionPointByLane_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 2, 4, 2, 5, 2, 6}, []string{"api", "v1", "traffic", "history_hour", "detection_point", "lane", "download"}, ""))
)

var (
	forward_HistoryHourTrafficDataByDetectionPointByLaneService_ListHistoryHourTrafficDataByDetectionPointByLane_0 = runtime.ForwardResponseMessage

	forward_HistoryHourTrafficDataByDetectionPointByLaneService_GetHistoryHourTrafficDataByDetectionPointByLane_0 = runtime.ForwardResponseMessage

	forward_HistoryHourTrafficDataByDetectionPointByLaneService_CreateHistoryHourTrafficDataByDetectionPointByLane_0 = runtime.ForwardResponseMessage

	forward_HistoryHourTrafficDataByDetectionPointByLaneService_UpdateHistoryHourTrafficDataByDetectionPointByLane_0 = runtime.ForwardResponseMessage

	forward_HistoryHourTrafficDataByDetectionPointByLaneService_DeleteHistoryHourTrafficDataByDetectionPointByLane_0 = runtime.ForwardResponseMessage

	forward_HistoryHourTrafficDataByDetectionPointByLaneService_BulkCreateHistoryHourTrafficDataByDetectionPointByLane_0 = runtime.ForwardResponseMessage

	forward_HistoryHourTrafficDataByDetectionPointByLaneService_GetHistoryHourTrafficDataByDetectionPointByLaneStatistics_0 = runtime.ForwardResponseMessage

	forward_HistoryHourTrafficDataByDetectionPointByLaneService_ListHistoryHourTrafficDataByDetectionPointByLaneDaily_0 = runtime.ForwardResponseMessage

	forward_HistoryHourTrafficDataByDetectionPointByLaneService_DownloadHistoryHourTrafficDataByDetectionPointByLane_0 = runtime.ForwardResponseMessage
)
