// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: services/dashboard.service.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DashboardGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardGetRequest) Reset() {
	*x = DashboardGetRequest{}
	mi := &file_services_dashboard_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardGetRequest) ProtoMessage() {}

func (x *DashboardGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_dashboard_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardGetRequest.ProtoReflect.Descriptor instead.
func (*DashboardGetRequest) Descriptor() ([]byte, []int) {
	return file_services_dashboard_service_proto_rawDescGZIP(), []int{0}
}

func (x *DashboardGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DashboardDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardDeleteRequest) Reset() {
	*x = DashboardDeleteRequest{}
	mi := &file_services_dashboard_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardDeleteRequest) ProtoMessage() {}

func (x *DashboardDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_dashboard_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardDeleteRequest.ProtoReflect.Descriptor instead.
func (*DashboardDeleteRequest) Descriptor() ([]byte, []int) {
	return file_services_dashboard_service_proto_rawDescGZIP(), []int{1}
}

func (x *DashboardDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DashboardListParams struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DataSourceName string                 `protobuf:"bytes,1,opt,name=data_source_name,json=dataSourceName,proto3" json:"data_source_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DashboardListParams) Reset() {
	*x = DashboardListParams{}
	mi := &file_services_dashboard_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardListParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardListParams) ProtoMessage() {}

func (x *DashboardListParams) ProtoReflect() protoreflect.Message {
	mi := &file_services_dashboard_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardListParams.ProtoReflect.Descriptor instead.
func (*DashboardListParams) Descriptor() ([]byte, []int) {
	return file_services_dashboard_service_proto_rawDescGZIP(), []int{2}
}

func (x *DashboardListParams) GetDataSourceName() string {
	if x != nil {
		return x.DataSourceName
	}
	return ""
}

type DashboardListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dashboard     []*Dashboard           `protobuf:"bytes,1,rep,name=dashboard,proto3" json:"dashboard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardListResponse) Reset() {
	*x = DashboardListResponse{}
	mi := &file_services_dashboard_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardListResponse) ProtoMessage() {}

func (x *DashboardListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_dashboard_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardListResponse.ProtoReflect.Descriptor instead.
func (*DashboardListResponse) Descriptor() ([]byte, []int) {
	return file_services_dashboard_service_proto_rawDescGZIP(), []int{3}
}

func (x *DashboardListResponse) GetDashboard() []*Dashboard {
	if x != nil {
		return x.Dashboard
	}
	return nil
}

var File_services_dashboard_service_proto protoreflect.FileDescriptor

const file_services_dashboard_service_proto_rawDesc = "" +
	"\n" +
	" services/dashboard.service.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x14dtos/dashboard.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"%\n" +
	"\x13DashboardGetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"(\n" +
	"\x16DashboardDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"?\n" +
	"\x13DashboardListParams\x12(\n" +
	"\x10data_source_name\x18\x01 \x01(\tR\x0edataSourceName\"D\n" +
	"\x15DashboardListResponse\x12+\n" +
	"\tdashboard\x18\x01 \x03(\v2\r.pb.DashboardR\tdashboard2\xf7\x03\n" +
	"\x10DashboardService\x12f\n" +
	"\x04List\x12\x17.pb.DashboardListParams\x1a\x19.pb.DashboardListResponse\"*\x92A\x0eb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/dashboard\x12^\n" +
	"\x03Get\x12\x17.pb.DashboardGetRequest\x1a\r.pb.Dashboard\"/\x92A\x0eb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/dashboard/{id}\x12U\n" +
	"\x06Create\x12\r.pb.Dashboard\x1a\r.pb.Dashboard\"-\x92A\x0eb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/v1/dashboard\x12U\n" +
	"\x06Update\x12\r.pb.Dashboard\x1a\r.pb.Dashboard\"-\x92A\x0eb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/api/v1/dashboard\x12m\n" +
	"\x06Delete\x12\x1a.pb.DashboardDeleteRequest\x1a\x16.google.protobuf.Empty\"/\x92A\x0eb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x02\x18*\x16/api/v1/dashboard/{id}B\x82\x01\x92AiZY\n" +
	"W\n" +
	"\x06bearer\x12M\b\x02\x128Authentication token, prefixed by Bearer: Bearer <token>\x1a\rAuthorization \x02b\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00Z\x14internal/metadata/pbb\x06proto3"

var (
	file_services_dashboard_service_proto_rawDescOnce sync.Once
	file_services_dashboard_service_proto_rawDescData []byte
)

func file_services_dashboard_service_proto_rawDescGZIP() []byte {
	file_services_dashboard_service_proto_rawDescOnce.Do(func() {
		file_services_dashboard_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_dashboard_service_proto_rawDesc), len(file_services_dashboard_service_proto_rawDesc)))
	})
	return file_services_dashboard_service_proto_rawDescData
}

var file_services_dashboard_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_services_dashboard_service_proto_goTypes = []any{
	(*DashboardGetRequest)(nil),    // 0: pb.DashboardGetRequest
	(*DashboardDeleteRequest)(nil), // 1: pb.DashboardDeleteRequest
	(*DashboardListParams)(nil),    // 2: pb.DashboardListParams
	(*DashboardListResponse)(nil),  // 3: pb.DashboardListResponse
	(*Dashboard)(nil),              // 4: pb.Dashboard
	(*emptypb.Empty)(nil),          // 5: google.protobuf.Empty
}
var file_services_dashboard_service_proto_depIdxs = []int32{
	4, // 0: pb.DashboardListResponse.dashboard:type_name -> pb.Dashboard
	2, // 1: pb.DashboardService.List:input_type -> pb.DashboardListParams
	0, // 2: pb.DashboardService.Get:input_type -> pb.DashboardGetRequest
	4, // 3: pb.DashboardService.Create:input_type -> pb.Dashboard
	4, // 4: pb.DashboardService.Update:input_type -> pb.Dashboard
	1, // 5: pb.DashboardService.Delete:input_type -> pb.DashboardDeleteRequest
	3, // 6: pb.DashboardService.List:output_type -> pb.DashboardListResponse
	4, // 7: pb.DashboardService.Get:output_type -> pb.Dashboard
	4, // 8: pb.DashboardService.Create:output_type -> pb.Dashboard
	4, // 9: pb.DashboardService.Update:output_type -> pb.Dashboard
	5, // 10: pb.DashboardService.Delete:output_type -> google.protobuf.Empty
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_services_dashboard_service_proto_init() }
func file_services_dashboard_service_proto_init() {
	if File_services_dashboard_service_proto != nil {
		return
	}
	file_dtos_dashboard_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_dashboard_service_proto_rawDesc), len(file_services_dashboard_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_dashboard_service_proto_goTypes,
		DependencyIndexes: file_services_dashboard_service_proto_depIdxs,
		MessageInfos:      file_services_dashboard_service_proto_msgTypes,
	}.Build()
	File_services_dashboard_service_proto = out.File
	file_services_dashboard_service_proto_goTypes = nil
	file_services_dashboard_service_proto_depIdxs = nil
}
