// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: services/detection_point.service.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDetectionPointRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DatasourceName string                 `protobuf:"bytes,1,opt,name=datasource_name,json=datasourceName,proto3" json:"datasource_name,omitempty"`
	DetectionPoint *DetectionPoint        `protobuf:"bytes,2,opt,name=detection_point,json=detectionPoint,proto3" json:"detection_point,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateDetectionPointRequest) Reset() {
	*x = CreateDetectionPointRequest{}
	mi := &file_services_detection_point_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDetectionPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDetectionPointRequest) ProtoMessage() {}

func (x *CreateDetectionPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_detection_point_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDetectionPointRequest.ProtoReflect.Descriptor instead.
func (*CreateDetectionPointRequest) Descriptor() ([]byte, []int) {
	return file_services_detection_point_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDetectionPointRequest) GetDatasourceName() string {
	if x != nil {
		return x.DatasourceName
	}
	return ""
}

func (x *CreateDetectionPointRequest) GetDetectionPoint() *DetectionPoint {
	if x != nil {
		return x.DetectionPoint
	}
	return nil
}

type CreateManyDetectionPointRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DatasourceName string                 `protobuf:"bytes,1,opt,name=datasource_name,json=datasourceName,proto3" json:"datasource_name,omitempty"`
	DetectionPoint []*DetectionPoint      `protobuf:"bytes,2,rep,name=detection_point,json=detectionPoint,proto3" json:"detection_point,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateManyDetectionPointRequest) Reset() {
	*x = CreateManyDetectionPointRequest{}
	mi := &file_services_detection_point_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateManyDetectionPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateManyDetectionPointRequest) ProtoMessage() {}

func (x *CreateManyDetectionPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_detection_point_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateManyDetectionPointRequest.ProtoReflect.Descriptor instead.
func (*CreateManyDetectionPointRequest) Descriptor() ([]byte, []int) {
	return file_services_detection_point_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateManyDetectionPointRequest) GetDatasourceName() string {
	if x != nil {
		return x.DatasourceName
	}
	return ""
}

func (x *CreateManyDetectionPointRequest) GetDetectionPoint() []*DetectionPoint {
	if x != nil {
		return x.DetectionPoint
	}
	return nil
}

// Response indicating the status of the operation
type CreateManyDetectionPointsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                       // Indicates if the operation was successful
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                        // Additional information about the operation
	DetectionPoints []*DetectionPoint      `protobuf:"bytes,3,rep,name=detection_points,json=detectionPoints,proto3" json:"detection_points,omitempty"` // List of detection points created
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateManyDetectionPointsResponse) Reset() {
	*x = CreateManyDetectionPointsResponse{}
	mi := &file_services_detection_point_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateManyDetectionPointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateManyDetectionPointsResponse) ProtoMessage() {}

func (x *CreateManyDetectionPointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_detection_point_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateManyDetectionPointsResponse.ProtoReflect.Descriptor instead.
func (*CreateManyDetectionPointsResponse) Descriptor() ([]byte, []int) {
	return file_services_detection_point_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateManyDetectionPointsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateManyDetectionPointsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateManyDetectionPointsResponse) GetDetectionPoints() []*DetectionPoint {
	if x != nil {
		return x.DetectionPoints
	}
	return nil
}

type UpdateDetectionPointRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DatasourceName string                 `protobuf:"bytes,1,opt,name=datasource_name,json=datasourceName,proto3" json:"datasource_name,omitempty"`
	DetectionPoint *DetectionPoint        `protobuf:"bytes,2,opt,name=detection_point,json=detectionPoint,proto3" json:"detection_point,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateDetectionPointRequest) Reset() {
	*x = UpdateDetectionPointRequest{}
	mi := &file_services_detection_point_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDetectionPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDetectionPointRequest) ProtoMessage() {}

func (x *UpdateDetectionPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_detection_point_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDetectionPointRequest.ProtoReflect.Descriptor instead.
func (*UpdateDetectionPointRequest) Descriptor() ([]byte, []int) {
	return file_services_detection_point_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateDetectionPointRequest) GetDatasourceName() string {
	if x != nil {
		return x.DatasourceName
	}
	return ""
}

func (x *UpdateDetectionPointRequest) GetDetectionPoint() *DetectionPoint {
	if x != nil {
		return x.DetectionPoint
	}
	return nil
}

type DeleteDetectionPointRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DatasourceName string                 `protobuf:"bytes,1,opt,name=datasource_name,json=datasourceName,proto3" json:"datasource_name,omitempty"`
	Id             string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteDetectionPointRequest) Reset() {
	*x = DeleteDetectionPointRequest{}
	mi := &file_services_detection_point_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDetectionPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDetectionPointRequest) ProtoMessage() {}

func (x *DeleteDetectionPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_detection_point_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDetectionPointRequest.ProtoReflect.Descriptor instead.
func (*DeleteDetectionPointRequest) Descriptor() ([]byte, []int) {
	return file_services_detection_point_service_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteDetectionPointRequest) GetDatasourceName() string {
	if x != nil {
		return x.DatasourceName
	}
	return ""
}

func (x *DeleteDetectionPointRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDetectionPointRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DatasourceName string                 `protobuf:"bytes,1,opt,name=datasource_name,json=datasourceName,proto3" json:"datasource_name,omitempty"`
	Id             string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetDetectionPointRequest) Reset() {
	*x = GetDetectionPointRequest{}
	mi := &file_services_detection_point_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDetectionPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDetectionPointRequest) ProtoMessage() {}

func (x *GetDetectionPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_detection_point_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDetectionPointRequest.ProtoReflect.Descriptor instead.
func (*GetDetectionPointRequest) Descriptor() ([]byte, []int) {
	return file_services_detection_point_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetDetectionPointRequest) GetDatasourceName() string {
	if x != nil {
		return x.DatasourceName
	}
	return ""
}

func (x *GetDetectionPointRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListDetectionPointsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DatasourceName string                 `protobuf:"bytes,1,opt,name=datasource_name,json=datasourceName,proto3" json:"datasource_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListDetectionPointsRequest) Reset() {
	*x = ListDetectionPointsRequest{}
	mi := &file_services_detection_point_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDetectionPointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDetectionPointsRequest) ProtoMessage() {}

func (x *ListDetectionPointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_detection_point_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDetectionPointsRequest.ProtoReflect.Descriptor instead.
func (*ListDetectionPointsRequest) Descriptor() ([]byte, []int) {
	return file_services_detection_point_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListDetectionPointsRequest) GetDatasourceName() string {
	if x != nil {
		return x.DatasourceName
	}
	return ""
}

type ListDetectionPointsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DatasourceName  string                 `protobuf:"bytes,1,opt,name=datasource_name,json=datasourceName,proto3" json:"datasource_name,omitempty"`
	DetectionPoints []*DetectionPoint      `protobuf:"bytes,2,rep,name=detection_points,json=detectionPoints,proto3" json:"detection_points,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListDetectionPointsResponse) Reset() {
	*x = ListDetectionPointsResponse{}
	mi := &file_services_detection_point_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDetectionPointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDetectionPointsResponse) ProtoMessage() {}

func (x *ListDetectionPointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_detection_point_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDetectionPointsResponse.ProtoReflect.Descriptor instead.
func (*ListDetectionPointsResponse) Descriptor() ([]byte, []int) {
	return file_services_detection_point_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListDetectionPointsResponse) GetDatasourceName() string {
	if x != nil {
		return x.DatasourceName
	}
	return ""
}

func (x *ListDetectionPointsResponse) GetDetectionPoints() []*DetectionPoint {
	if x != nil {
		return x.DetectionPoints
	}
	return nil
}

type BulkDetectionPointRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DatasourceName string                 `protobuf:"bytes,1,opt,name=datasource_name,json=datasourceName,proto3" json:"datasource_name,omitempty"`
	File           *File                  `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"` // File containing detection points in JSON format
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BulkDetectionPointRequest) Reset() {
	*x = BulkDetectionPointRequest{}
	mi := &file_services_detection_point_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkDetectionPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkDetectionPointRequest) ProtoMessage() {}

func (x *BulkDetectionPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_detection_point_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkDetectionPointRequest.ProtoReflect.Descriptor instead.
func (*BulkDetectionPointRequest) Descriptor() ([]byte, []int) {
	return file_services_detection_point_service_proto_rawDescGZIP(), []int{8}
}

func (x *BulkDetectionPointRequest) GetDatasourceName() string {
	if x != nil {
		return x.DatasourceName
	}
	return ""
}

func (x *BulkDetectionPointRequest) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

type BulkDetectionPointResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DetectionPoints []*DetectionPoint      `protobuf:"bytes,1,rep,name=detection_points,json=detectionPoints,proto3" json:"detection_points,omitempty"` // List of detection points created
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BulkDetectionPointResponse) Reset() {
	*x = BulkDetectionPointResponse{}
	mi := &file_services_detection_point_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkDetectionPointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkDetectionPointResponse) ProtoMessage() {}

func (x *BulkDetectionPointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_detection_point_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkDetectionPointResponse.ProtoReflect.Descriptor instead.
func (*BulkDetectionPointResponse) Descriptor() ([]byte, []int) {
	return file_services_detection_point_service_proto_rawDescGZIP(), []int{9}
}

func (x *BulkDetectionPointResponse) GetDetectionPoints() []*DetectionPoint {
	if x != nil {
		return x.DetectionPoints
	}
	return nil
}

var File_services_detection_point_service_proto protoreflect.FileDescriptor

const file_services_detection_point_service_proto_rawDesc = "" +
	"\n" +
	"&services/detection_point.service.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\x1a\x1adtos/detection_point.proto\x1a\x0fdtos/file.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x83\x01\n" +
	"\x1bCreateDetectionPointRequest\x12'\n" +
	"\x0fdatasource_name\x18\x01 \x01(\tR\x0edatasourceName\x12;\n" +
	"\x0fdetection_point\x18\x02 \x01(\v2\x12.pb.DetectionPointR\x0edetectionPoint\"\x87\x01\n" +
	"\x1fCreateManyDetectionPointRequest\x12'\n" +
	"\x0fdatasource_name\x18\x01 \x01(\tR\x0edatasourceName\x12;\n" +
	"\x0fdetection_point\x18\x02 \x03(\v2\x12.pb.DetectionPointR\x0edetectionPoint\"\x96\x01\n" +
	"!CreateManyDetectionPointsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12=\n" +
	"\x10detection_points\x18\x03 \x03(\v2\x12.pb.DetectionPointR\x0fdetectionPoints\"\x83\x01\n" +
	"\x1bUpdateDetectionPointRequest\x12'\n" +
	"\x0fdatasource_name\x18\x01 \x01(\tR\x0edatasourceName\x12;\n" +
	"\x0fdetection_point\x18\x02 \x01(\v2\x12.pb.DetectionPointR\x0edetectionPoint\"V\n" +
	"\x1bDeleteDetectionPointRequest\x12'\n" +
	"\x0fdatasource_name\x18\x01 \x01(\tR\x0edatasourceName\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"S\n" +
	"\x18GetDetectionPointRequest\x12'\n" +
	"\x0fdatasource_name\x18\x01 \x01(\tR\x0edatasourceName\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"E\n" +
	"\x1aListDetectionPointsRequest\x12'\n" +
	"\x0fdatasource_name\x18\x01 \x01(\tR\x0edatasourceName\"\x85\x01\n" +
	"\x1bListDetectionPointsResponse\x12'\n" +
	"\x0fdatasource_name\x18\x01 \x01(\tR\x0edatasourceName\x12=\n" +
	"\x10detection_points\x18\x02 \x03(\v2\x12.pb.DetectionPointR\x0fdetectionPoints\"b\n" +
	"\x19BulkDetectionPointRequest\x12'\n" +
	"\x0fdatasource_name\x18\x01 \x01(\tR\x0edatasourceName\x12\x1c\n" +
	"\x04file\x18\x02 \x01(\v2\b.pb.FileR\x04file\"[\n" +
	"\x1aBulkDetectionPointResponse\x12=\n" +
	"\x10detection_points\x18\x01 \x03(\v2\x12.pb.DetectionPointR\x0fdetectionPoints2\xf8\n" +
	"\n" +
	"\x15DetectionPointService\x12\xa6\x01\n" +
	"\x13ListDetectionPoints\x12\x1e.pb.ListDetectionPointsRequest\x1a\x1f.pb.ListDetectionPointsResponse\"N\x92A\x0eb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x027\x125/api/v1/datasource/{datasource_name}/detection_points\x12\x9a\x01\n" +
	"\x11GetDetectionPoint\x12\x1c.pb.GetDetectionPointRequest\x1a\x12.pb.DetectionPoint\"S\x92A\x0eb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x02<\x12:/api/v1/datasource/{datasource_name}/detection_points/{id}\x12\x9f\x01\n" +
	"\x15CreateDetectionPoints\x12\x1f.pb.CreateDetectionPointRequest\x1a\x12.pb.DetectionPoint\"Q\x92A\x0eb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x02::\x01*\"5/api/v1/datasource/{datasource_name}/detection_points\x12\xbf\x01\n" +
	"\x19CreateManyDetectionPoints\x12#.pb.CreateManyDetectionPointRequest\x1a%.pb.CreateManyDetectionPointsResponse\"V\x92A\x0eb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x02?:\x01*\":/api/v1/datasource/{datasource_name}/many_detection_points\x12\x9e\x01\n" +
	"\x14UpdateDetectionPoint\x12\x1f.pb.UpdateDetectionPointRequest\x1a\x12.pb.DetectionPoint\"Q\x92A\x0eb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x02::\x01*\x1a5/api/v1/datasource/{datasource_name}/detection_points\x12\xa4\x01\n" +
	"\x14DeleteDetectionPoint\x12\x1f.pb.DeleteDetectionPointRequest\x1a\x16.google.protobuf.Empty\"S\x92A\x0eb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x02<*:/api/v1/datasource/{datasource_name}/detection_points/{id}\x12\xa2\x01\n" +
	"\x17DeleteAllDetectionPoint\x12\x1f.pb.DeleteDetectionPointRequest\x1a\x16.google.protobuf.Empty\"N\x92A\x0eb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x027*5/api/v1/datasource/{datasource_name}/detection_points\x12\xc7\x01\n" +
	"\x19BulkCreateDetectionPoints\x12\x1d.pb.BulkDetectionPointRequest\x1a\x1e.pb.BulkDetectionPointResponse\"k\x92A#2\x13multipart/form-datab\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x02?:\x01*\":/api/v1/datasource/{datasource_name}/detection_points/bulkB\x82\x01\x92AiZY\n" +
	"W\n" +
	"\x06bearer\x12M\b\x02\x128Authentication token, prefixed by Bearer: Bearer <token>\x1a\rAuthorization \x02b\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00Z\x14internal/metadata/pbb\x06proto3"

var (
	file_services_detection_point_service_proto_rawDescOnce sync.Once
	file_services_detection_point_service_proto_rawDescData []byte
)

func file_services_detection_point_service_proto_rawDescGZIP() []byte {
	file_services_detection_point_service_proto_rawDescOnce.Do(func() {
		file_services_detection_point_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_detection_point_service_proto_rawDesc), len(file_services_detection_point_service_proto_rawDesc)))
	})
	return file_services_detection_point_service_proto_rawDescData
}

var file_services_detection_point_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_services_detection_point_service_proto_goTypes = []any{
	(*CreateDetectionPointRequest)(nil),       // 0: pb.CreateDetectionPointRequest
	(*CreateManyDetectionPointRequest)(nil),   // 1: pb.CreateManyDetectionPointRequest
	(*CreateManyDetectionPointsResponse)(nil), // 2: pb.CreateManyDetectionPointsResponse
	(*UpdateDetectionPointRequest)(nil),       // 3: pb.UpdateDetectionPointRequest
	(*DeleteDetectionPointRequest)(nil),       // 4: pb.DeleteDetectionPointRequest
	(*GetDetectionPointRequest)(nil),          // 5: pb.GetDetectionPointRequest
	(*ListDetectionPointsRequest)(nil),        // 6: pb.ListDetectionPointsRequest
	(*ListDetectionPointsResponse)(nil),       // 7: pb.ListDetectionPointsResponse
	(*BulkDetectionPointRequest)(nil),         // 8: pb.BulkDetectionPointRequest
	(*BulkDetectionPointResponse)(nil),        // 9: pb.BulkDetectionPointResponse
	(*DetectionPoint)(nil),                    // 10: pb.DetectionPoint
	(*File)(nil),                              // 11: pb.File
	(*emptypb.Empty)(nil),                     // 12: google.protobuf.Empty
}
var file_services_detection_point_service_proto_depIdxs = []int32{
	10, // 0: pb.CreateDetectionPointRequest.detection_point:type_name -> pb.DetectionPoint
	10, // 1: pb.CreateManyDetectionPointRequest.detection_point:type_name -> pb.DetectionPoint
	10, // 2: pb.CreateManyDetectionPointsResponse.detection_points:type_name -> pb.DetectionPoint
	10, // 3: pb.UpdateDetectionPointRequest.detection_point:type_name -> pb.DetectionPoint
	10, // 4: pb.ListDetectionPointsResponse.detection_points:type_name -> pb.DetectionPoint
	11, // 5: pb.BulkDetectionPointRequest.file:type_name -> pb.File
	10, // 6: pb.BulkDetectionPointResponse.detection_points:type_name -> pb.DetectionPoint
	6,  // 7: pb.DetectionPointService.ListDetectionPoints:input_type -> pb.ListDetectionPointsRequest
	5,  // 8: pb.DetectionPointService.GetDetectionPoint:input_type -> pb.GetDetectionPointRequest
	0,  // 9: pb.DetectionPointService.CreateDetectionPoints:input_type -> pb.CreateDetectionPointRequest
	1,  // 10: pb.DetectionPointService.CreateManyDetectionPoints:input_type -> pb.CreateManyDetectionPointRequest
	3,  // 11: pb.DetectionPointService.UpdateDetectionPoint:input_type -> pb.UpdateDetectionPointRequest
	4,  // 12: pb.DetectionPointService.DeleteDetectionPoint:input_type -> pb.DeleteDetectionPointRequest
	4,  // 13: pb.DetectionPointService.DeleteAllDetectionPoint:input_type -> pb.DeleteDetectionPointRequest
	8,  // 14: pb.DetectionPointService.BulkCreateDetectionPoints:input_type -> pb.BulkDetectionPointRequest
	7,  // 15: pb.DetectionPointService.ListDetectionPoints:output_type -> pb.ListDetectionPointsResponse
	10, // 16: pb.DetectionPointService.GetDetectionPoint:output_type -> pb.DetectionPoint
	10, // 17: pb.DetectionPointService.CreateDetectionPoints:output_type -> pb.DetectionPoint
	2,  // 18: pb.DetectionPointService.CreateManyDetectionPoints:output_type -> pb.CreateManyDetectionPointsResponse
	10, // 19: pb.DetectionPointService.UpdateDetectionPoint:output_type -> pb.DetectionPoint
	12, // 20: pb.DetectionPointService.DeleteDetectionPoint:output_type -> google.protobuf.Empty
	12, // 21: pb.DetectionPointService.DeleteAllDetectionPoint:output_type -> google.protobuf.Empty
	9,  // 22: pb.DetectionPointService.BulkCreateDetectionPoints:output_type -> pb.BulkDetectionPointResponse
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_services_detection_point_service_proto_init() }
func file_services_detection_point_service_proto_init() {
	if File_services_detection_point_service_proto != nil {
		return
	}
	file_dtos_detection_point_proto_init()
	file_dtos_file_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_detection_point_service_proto_rawDesc), len(file_services_detection_point_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_detection_point_service_proto_goTypes,
		DependencyIndexes: file_services_detection_point_service_proto_depIdxs,
		MessageInfos:      file_services_detection_point_service_proto_msgTypes,
	}.Build()
	File_services_detection_point_service_proto = out.File
	file_services_detection_point_service_proto_goTypes = nil
	file_services_detection_point_service_proto_depIdxs = nil
}
